Fix: Native mappings that clashed with plugins, checked the plugin pe…
SpongePowered/Sponge pull request #1008
Opened 2016-11-01 08:52 UTC by ryantheleach

…rmission, not the native permission.

Fixes:

https://forums.spongepowered.org/t/0-13-1-nucleus-the-ultimate-essentials-plugin-mc-1-8-9-and-1-10-2/11792/745

When checking the commandMapping this was unintentionally pulling the mapping for Nucleus.

Not 100% happy with this solution.
 Should we instead have a separate registry just for the command mappings with wrapped callables?

2016-11-01 08:56 UTC, ryantheleach commented on src/main/java/org/spongepowered/common/command/CommandPermissions.java
> -                return callable.testPermission(source);
This else seemed to be unused / useless as this method was only ever called on native commands.

2016-11-01 08:59 UTC, kashike requested changes

2016-11-01 08:59 UTC, kashike commented on src/main/java/org/spongepowered/common/command/CommandPermissions.java
> +        if(nativeMappings.size() > 1) throw new IllegalStateException("Only one native mapping expected for "+commandName);
`if (` (space), missing braces

2016-11-02 10:12 UTC, ryantheleach commented
I've done some quick testing by loading up HermitPack in single player production environment and testing using /help which calls a permission check for each of the commands in order to display them.

Additionally I've tested this without mods in a debugger using the /forge command.

Loaded up nucleus in a production SF environment with LuckPerms, /enchant works with nucleus.enchant.base /minecraft:enchant No permission.

Seems to work nicely.

2016-11-02 10:22 UTC, kashike approved these changes

2016-11-02 10:23 UTC, kashike commented on src/main/java/org/spongepowered/common/command/CommandPermissions.java
> +            throw new IllegalStateException("Only one native mapping expected for " + commandName);
Perhaps specify how many were found.

2016-11-02 11:29 UTC, JBYoshi requested changes

2016-11-02 11:29 UTC, JBYoshi commented on src/main/java/org/spongepowered/common/command/CommandPermissions.java
> +        //Possible I guess, if some plugin (not mod) intentionally re-registers a minecraft/mod command under a clashing alias...
I'd like to verify this; if I have time I'll check later today.

2016-11-02 11:29 UTC, JBYoshi commented on src/main/java/org/spongepowered/common/command/CommandPermissions.java
> +            throw new IllegalStateException("Only one native mapping expected for /" + commandName+"found "+size +"("+ commaSeparated +")");
This line needs a few formatting fixes.

2016-11-02 22:22 UTC, JBYoshi requested changes

2016-11-02 22:22 UTC, JBYoshi commented on src/main/java/org/spongepowered/common/command/CommandPermissions.java
> +        //Possible I guess, if some plugin (not mod) intentionally re-registers a minecraft/mod command under a clashing alias...
There will be multiple items in `nativeMappings` if there is a name clash. The fix for this (other than preventing conflicting native commands altogether) is to somehow pass the command from `CommandBase.testPermission()` to this method. I'd use a `ThreadLocal` for this; there's some example code in `MinecraftCommandWrapper` which I used to propagate exceptions in commands through Minecraft back to Sponge if you want to do it.

Here's some test code for a conflicting command:

``` java
import net.minecraft.command.*;
import net.minecraft.server.MinecraftServer;
import net.minecraft.util.text.TextComponentString;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.event.FMLServerStartingEvent;
import java.util.*;

@Mod(modid="spongepermissiontestforge")
public class SpongePermissionTestForge {
    @Mod.EventHandler
    public void onFMLServerStarting(FMLServerStartingEvent event) {
        event.registerServerCommand(new CommandBase() {
            @Override public String getCommandName() {return "tp";}
            @Override public String getCommandUsage(ICommandSender sender) {return "/tp from Forge mod";}
            @Override public void execute(MinecraftServer server, ICommandSender sender, String[] args) throws CommandException {sender.addChatMessage(new TextComponentString("Forge mod command"));}
        });
    }
}
```

2016-11-02 23:55 UTC, ryantheleach commented on src/main/java/org/spongepowered/common/command/CommandPermissions.java
> +        //Possible I guess, if some plugin (not mod) intentionally re-registers a minecraft/mod command under a clashing alias...
Hey JBYoshi, will probably get around to testing this, this afternoon.

But just wanted to ask if you had tested this? From what I could see (without testing purposely clashing forge commands) is that forge will overwrite the tp mapping with SpongePermissionTestForge's permission mapping.

So unless this is covered by a mixin somewhere it should be fine?

Anyway I'll try to get around to compiling this test-mod at some stage to have hard imperative proof one way or another.

2017-06-11 09:24 UTC, ryantheleach commented
Closed in: https://github.com/SpongePowered/SpongeCommon/pull/1262 ?

2017-06-11 09:24 UTC, closed without merging