PaginationService doesn't support \n
SpongePowered/Sponge pull request #1020
Opened 2016-11-11 20:57 UTC by rexbut

The pagination service doesn't support the character "\n". With the character " \n", the number of line is different to the real number of line.

- **Before :**

![Error_1](http://image.noelshack.com/fichiers/2016/45/1478897462-pagination-erreur-2.png)
![Error_2](http://image.noelshack.com/fichiers/2016/45/1478897463-pagination-erreur-1.png)

- **After :**

![Fix_1](http://image.noelshack.com/fichiers/2016/45/1478897457-pagination-correction-1.png)
![Fix_2](http://image.noelshack.com/fichiers/2016/45/1478897462-pagination-correction-2.png)

2016-11-11 23:13 UTC, simon816 commented on src/main/java/org/spongepowered/common/service/pagination/PaginationCalculator.java
> +                if (cp == 10) {
Would be more clear to use `'\n'` here instead of `10`

2016-12-25 20:29 UTC, windy1 submitted a review, later dismissed
Just tested this. The issue I found looks to be that you don't iterate over the text children deeply, meaning it will only pick up newlines on the top children level.

2017-01-17 18:52 UTC, Minecrell commented
@windy1 That is weird because the code uses `Text.withChildren()` which provides an recursive iterator over all children of a Text instance. It should process all children correctly.

2017-01-17 18:57 UTC, windy1 commented
I could be wrong then, I wasn't aware of that and that was really more of a (not so) educated guess, however I tested with nested text with newlines in them and it didn't work :/

2017-01-17 21:03 UTC, rexbut commented
@windy1 Didn't worked when there was /n several times.

2017-01-18 05:45 UTC, kashike requested changes

2017-01-18 05:45 UTC, kashike commented on src/main/java/org/spongepowered/common/service/pagination/PaginationCalculator.java
> +            boolean new_line = false;
This should be called `newLine`, not `new_line`.

2017-01-18 06:07 UTC, kashike approved these changes

2017-02-07 19:56 UTC, randombyte-developer commented
This also seems to fix an issue with headers(probably footers too): When having a multiline header the pages get to long. The fixed `getWidth()` should fix that.

2017-03-03 17:46 UTC, merged