[WIP] Implement Recipes
SpongePowered/Sponge pull request #1027
Opened 2016-11-19 22:55 UTC by Maxqia

[API](url) | **Common**

2016-11-19 23:07 UTC, kashike requested changes

2016-11-19 23:07 UTC, kashike commented on src/main/java/org/spongepowered/common/mixin/core/item/recipe/MixinFurnaceRecipies.java
> +package org.spongepowered.common.mixin.core.item.recipe;
Missing licence header.

2016-11-19 23:07 UTC, kashike commented on src/main/java/org/spongepowered/common/mixin/core/item/recipe/MixinFurnaceRecipies.java
> +import java.util.Map;
Wrong import order.

2016-11-19 23:07 UTC, kashike commented on src/main/java/org/spongepowered/common/mixin/core/item/recipe/MixinFurnaceRecipies.java
> +import net.minecraft.item.ItemStack;
Wrong import order.

2016-11-19 23:07 UTC, kashike commented on src/main/java/org/spongepowered/common/mixin/core/item/recipe/MixinFurnaceRecipies.java
> +        ItemStack stack = smeltingList.remove(input);
`this.`

2016-11-19 23:07 UTC, kashike commented on src/main/java/org/spongepowered/common/mixin/core/item/recipe/MixinFurnaceRecipies.java
> +        return ItemStackUtil.cloneDefensive(smeltingList.get(stack));
`this.`

2016-11-19 23:07 UTC, kashike commented on src/main/java/org/spongepowered/common/mixin/core/item/recipe/MixinFurnaceRecipies.java
> +        return experienceList.get(stack);
`this.`

2016-11-19 23:08 UTC, liach commented on src/main/java/org/spongepowered/common/mixin/core/item/recipe/MixinFurnaceRecipies.java
> +            throw new RuntimeException("It was in one map but not the other?");
```java
throw new AssertionError("It was on one map but not the other.");
```

2016-11-19 23:12 UTC, liach commented on src/main/java/org/spongepowered/common/mixin/core/item/recipe/MixinFurnaceRecipies.java
> +        addSmeltingRecipe(ItemStackUtil.toNative(input), ItemStackUtil.toNative(output), exp);
Is `toNative` simply for casting?

2016-11-19 23:13 UTC, liach commented
Why do you never update submodule?

2016-11-19 23:20 UTC, kashike commented on src/main/java/org/spongepowered/common/mixin/core/item/recipe/MixinFurnaceRecipies.java
> +        addSmeltingRecipe(ItemStackUtil.toNative(input), ItemStackUtil.toNative(output), exp);
Yes.

2016-11-20 03:33 UTC, Maxqia commented
Now with more testing!

2016-11-20 04:19 UTC, liach commented on src/main/java/org/spongepowered/common/mixin/core/item/recipe/MixinFurnaceRecipes.java
> +    public Optional<Float> getExperience(org.spongepowered.api.item.inventory.ItemStack stack) {
There should be an `OptionalDouble` available in `java.util`.

2016-11-20 04:50 UTC, Maxqia commented on src/main/java/org/spongepowered/common/mixin/core/item/recipe/MixinFurnaceRecipes.java
> +    public Optional<Float> getExperience(org.spongepowered.api.item.inventory.ItemStack stack) {
That exists?!? ..., but it's kind of stupid, it always says it's present even if it's null

2017-01-01 20:10 UTC, Limeth commented on src/main/java/org/spongepowered/common/item/recipe/SpongeSmeltingRecipe.java
> +        return this;
I am confused. This is not how builders are supposed to work.

2017-03-13 15:48 UTC, liach commented on src/main/java/org/spongepowered/common/item/recipe/crafting/SpongeShapedCraftingRecipeBuilder.java
> +    public static <T> ImmutableMap<T, ItemStackSnapshot> mapItemStackSnapshot(Map<T, ItemStack> map) {
These should move to util classes.

2017-03-13 15:50 UTC, liach commented on src/main/java/org/spongepowered/common/mixin/core/item/recipe/MixinCraftingManager.java
> +        throw new NotImplementedException("TODO"); // dunno how to convert a gridinventory to a IInventory...
:scream:

2017-03-13 15:51 UTC, liach commented on src/main/java/org/spongepowered/common/mixin/core/item/recipe/MixinIRecipe.java
> +    default ImmutableCollection<ItemStackSnapshot> getResults() {
Why are you using `ImmutableCollection`?

2017-06-17 01:10 UTC, kashike commented
I'm going to close this in favour of #1395.

2017-06-17 01:10 UTC, closed without merging