EnderDragon phases
SpongePowered/Sponge pull request #1032
Opened 2016-11-25 00:35 UTC by kashike

[API](https://github.com/SpongePowered/SpongeAPI/pull/1421) | [**Common**](https://github.com/SpongePowered/SpongeCommon/pull/1032)

2016-12-08 07:18 UTC, gabizou commented
@kashike I'm going to have to thoroughly go through this as I need to write handling for the CauseTracker to deal with the various phases and have direct spawning for a lot of things involved with dragon's phases. As such, this PR does have to interact with said system properly to avoid issues with tracking and capturing.

2017-04-21 05:35 UTC, gabizou requested changes
There is no registry module being used for the types, so as a `CatalogType`, this is failing implementation requirements.

2017-04-21 05:35 UTC, gabizou commented on src/main/java/org/spongepowered/common/mixin/core/entity/boss/dragon/phase/MixinIPhase.java
> +
What about implementing `getType()`?

2017-04-21 05:35 UTC, gabizou commented on src/main/java/org/spongepowered/common/mixin/core/entity/boss/dragon/phase/MixinPhaseList.java
> +public class MixinPhaseList implements EnderDragonPhaseType {
This is not implementing any of the existing methods from the type class.

2018-01-27 11:40 UTC, ryantheleach commented
This was stalled by an interaction with the old cause tracker, it should now be unblocked but needs to be updated for the new Phase/Cause Stack system.

2019-02-03 12:17 UTC, ImMorpheus commented
Updated.

Just need to figure this out.

```
Error while mapping org.spongepowered.api.entity.living.complex.dragon.phase.EnderDragonPhaseTypes.HOVER
java.lang.IllegalAccessException: Can not set static final org.spongepowered.api.entity.living.complex.dragon.phase.EnderDragonPhaseType field org.spongepowered.api.entity.living.complex.dragon.phase.EnderDragonPhaseTypes.HOVER to net.minecraft.entity.boss.dragon.phase.PhaseList
```

2019-02-03 16:59 UTC, merged