Utilise GitHub templates
SpongePowered/Sponge pull request #1059
Opened 2016-12-08 03:56 UTC by kashike

[**Common**]() | [Forge](https://github.com/SpongePowered/SpongeForge/pull/1089)

2016-12-08 07:12 UTC, gabizou commented
Mention something about crash logs.

2016-12-08 07:16 UTC, gabizou requested changes
We should mention about where to post the logs, considering a lot of issues can potentially be including logs from the CauseTracker.

2017-02-15 16:44 UTC, Zidane approved these changes

2017-02-18 05:39 UTC, gabizou approved these changes

2017-04-22 06:28 UTC, merged