Attributes
SpongePowered/Sponge pull request #1064
Opened 2016-12-09 21:59 UTC by kashike

[API](https://github.com/SpongePowered/SpongeAPI/pull/1428) | [**Common**](https://github.com/SpongePowered/SpongeAPI/pull/1064)

2016-12-14 19:52 UTC, liach commented on src/main/java/org/spongepowered/common/mixin/core/entity/ai/attributes/MixinAttributeModifier.java
> +@Implements(@Interface(iface = AttributeModifier.class, prefix = "modifier$"))
Why this?

2016-12-14 19:54 UTC, liach commented on src/main/java/org/spongepowered/common/registry/type/entity/AttributeOperationRegistryModule.java
> +    public final Map<String, AttributeOperation> operationMap = Maps.newHashMap();
Guava suggests you to use constructor since java7.

2016-12-14 23:17 UTC, Deamon5550 commented on src/main/java/org/spongepowered/common/registry/type/entity/AttributeOperationRegistryModule.java
> +    public final Map<String, AttributeOperation> operationMap = Maps.newHashMap();
Our practice across the entire repo is to use guava, not changing now.

2016-12-14 23:32 UTC, liach commented on src/main/java/org/spongepowered/common/registry/type/entity/AttributeRegistryModule.java
> +    private final Map<String, AttributeType> attributes = new HashMap<>();
@Deamon5550 Then why do you use constructor here if you always uses guava?

2016-12-14 23:34 UTC, liach commented on src/main/java/org/spongepowered/common/registry/type/entity/AttributeRegistryModule.java
> +    private final Map<String, AttributeType> attributes = new HashMap<>();
https://github.com/google/guava/blob/master/guava/src/com/google/common/collect/Sets.java#L210-L212

2017-04-25 16:00 UTC, gabizou requested changes
Your intrinsic methods need to have prefixes with `@Implements` annotated on the mixing class.

2017-04-25 16:00 UTC, gabizou commented on src/main/java/org/spongepowered/common/mixin/core/entity/ai/attributes/MixinIAttribute.java
> +    default double getDefaultValue() {
If this is intrinsic, it needs to be prefixed.

2017-04-25 16:00 UTC, gabizou commented on src/main/java/org/spongepowered/common/mixin/core/entity/ai/attributes/MixinIAttribute.java
> +    default String getName() {
If this is intrinsic, needs to be prefixed.

2018-01-27 11:42 UTC, ryantheleach commented
Kashike has some changes locally on this that need to be finished, If anyone picks this up, I'd recommend contacting them first to see what direction it was heading in.

2019-12-02 19:34 UTC, closed without merging

2019-12-02 19:37 UTC, gabizou commented
This will need to be re-done and re-target `api-8`. Bleeding is no longer a valid branch.