Add PortionData to Double Plants.
SpongePowered/Sponge pull request #1071
Opened 2016-12-12 13:31 UTC by me4502

This adds PortionData to DoublePlants.

I'm not entirely sure if this is necessary, but already did the changes so may as well create the PR, just incase it is required.

2016-12-12 13:33 UTC, kashike requested changes

2016-12-12 13:33 UTC, kashike commented on src/main/java/org/spongepowered/common/mixin/core/block/MixinBlockDoublePlant.java
> +                getPortionData(blockState));
This doesn't need to be on a new line.

2016-12-18 01:44 UTC, me4502 commented on src/main/java/org/spongepowered/common/mixin/core/block/MixinBlockDoublePlant.java
> +                getPortionData(blockState));
Fixed.

2016-12-21 18:46 UTC, gabizou approved these changes
Looks good.

2016-12-22 05:04 UTC, me4502 commented
Thanks, I'll do my final testing - as I've written a fair bit of extra code to test with since I did my last test.

2016-12-22 08:01 UTC, merged