Use the classloader from the object we got to avoid NoClassDefFoundErrors
SpongePowered/Sponge pull request #1090
Opened 2016-12-21 21:10 UTC by Maxqia

When trying to register a event class from a classloader different from
Sponge's, when we try to define the class, it throws a NoClassDefFoundError
due to the class being unaccessable from the current classloader.

2016-12-21 21:28 UTC, Deamon5550 requested changes

2016-12-21 21:28 UTC, Deamon5550 commented on src/main/java/org/spongepowered/common/event/SpongeEventManager.java
> +    private final Map<ClassLoader, AnnotatedEventListener.Factory> classLoaders = Maps.newHashMap();
This should be a loading cache with weak keys.

2016-12-22 03:26 UTC, Maxqia commented on src/main/java/org/spongepowered/common/event/SpongeEventManager.java
> +    private final Map<ClassLoader, AnnotatedEventListener.Factory> classLoaders = Maps.newHashMap();
Won't that just cause classloaders to be added like crazy?

2016-12-22 06:32 UTC, Deamon5550 commented on src/main/java/org/spongepowered/common/event/SpongeEventManager.java
> +    private final Map<ClassLoader, AnnotatedEventListener.Factory> classLoaders = Maps.newHashMap();
Keeps us from leaking a plugin's special classloader if they've released it to be garbage collected. Which is pretty common as when the classloader is garbage collected so is all of the classes it loaded.

2016-12-22 07:03 UTC, Maxqia commented on src/main/java/org/spongepowered/common/event/SpongeEventManager.java
> +    private final Map<ClassLoader, AnnotatedEventListener.Factory> classLoaders = Maps.newHashMap();
That wouldn't change that because we'd still have a store of the object (and therefore it's classloader) in the event handler.

2017-01-17 23:38 UTC, Deamon5550 approved these changes

2017-01-18 03:21 UTC, gabizou commented on src/main/java/org/spongepowered/common/event/SpongeEventManager.java
> +        registerListeners(getPlugin(plugin), listener);
How does this not cause a stack overflow?

2017-01-18 03:39 UTC, Maxqia commented on src/main/java/org/spongepowered/common/event/SpongeEventManager.java
> +        registerListeners(getPlugin(plugin), listener);
Java chooses the most specific method when overloading methods

2017-01-18 04:18 UTC, gabizou commented on src/main/java/org/spongepowered/common/event/SpongeEventManager.java
> +        registerListeners(getPlugin(plugin), listener);
Sure, but this is nonetheless, very very very ambiguous.

2018-01-28 22:38 UTC, vorburger commented
FYI I've done the (trivial) neccessary rebase of this PR in https://github.com/SpongePowered/SpongeCommon/compare/bleeding...vorburger:Maxqia-eventclassloader, but... it now fails the `ShouldFireTest` and `SnapshotGenerationTest` with this:

```
java.lang.IllegalArgumentException: Unknown plugin: Mock for PluginContainer, hashCode: 312890187
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191)
	at org.spongepowered.common.event.SpongeEventManager.getPlugin(SpongeEventManager.java:296)
```

I suspect that Mockito does ClassLoader magic and because of this _fix_ it makes that fail now...

2018-01-29 00:58 UTC, vorburger commented
> now fails the ShouldFireTest and SnapshotGenerationTest with this

nah that was just because I made a mistake in the rebase (registerListener*s*), now it passes.

I cannot update this PR, so proposing as new https://github.com/SpongePowered/SpongeCommon/pull/1737/

2018-01-29 01:00 UTC, vorburger commented on src/main/java/org/spongepowered/common/event/SpongeEventManager.java
> +        registerListeners(getPlugin(plugin), listener);
@gabizou in the reincarnation over on https://github.com/SpongePowered/SpongeCommon/pull/1737/ I've undone this part, if that helps to finally get this in? That also takes care of any possible backwards compatibility concerns.

2018-01-29 01:12 UTC, closed without merging