Implementation of AgeableData
SpongePowered/Sponge pull request #1092
Opened 2016-12-23 00:38 UTC by Maxqia

[API]() | **Common**
See #562 
Edited for 1.11 and for IS_ADULT to work correctly (instead of 1 tick)

2017-01-30 07:05 UTC, me4502 commented
From inspection this doesn't appear like it'd support Zombies, as they don't extend EntityAgeable.

2017-01-31 04:43 UTC, Maxqia commented
That should be fixed now.

2017-01-31 04:45 UTC, me4502 approved these changes

2017-01-31 08:36 UTC, gabizou commented on src/main/java/org/spongepowered/common/data/processor/multi/entity/AgeableDataProcessor.java
> +            if (age != null) {
In what case is the value null?

2017-01-31 08:41 UTC, gabizou commented on src/main/java/org/spongepowered/common/data/processor/value/entity/IsAdultValueProcessor.java
> +        Boolean rtr = false;
Why is this an object?

2017-02-08 06:41 UTC, me4502 commented on src/main/java/org/spongepowered/common/data/processor/multi/entity/AgeableDataProcessor.java
> +        } else /*if (entityCast instanceof EntityZombie)*/ { // commented so it doesn't throw an error
Wait, why would this throw an error?

2017-02-08 06:50 UTC, Maxqia commented on src/main/java/org/spongepowered/common/data/processor/multi/entity/AgeableDataProcessor.java
> +        } else /*if (entityCast instanceof EntityZombie)*/ { // commented so it doesn't throw an error
Variable isn't assigned error

2017-02-08 06:56 UTC, me4502 commented on src/main/java/org/spongepowered/common/data/processor/multi/entity/AgeableDataProcessor.java
> +        } else /*if (entityCast instanceof EntityZombie)*/ { // commented so it doesn't throw an error
entityCast isn't assigned there, but is prior?

2017-02-08 08:05 UTC, Maxqia commented on src/main/java/org/spongepowered/common/data/processor/multi/entity/AgeableDataProcessor.java
> +        } else /*if (entityCast instanceof EntityZombie)*/ { // commented so it doesn't throw an error
No, for int age and boolean adult...

2017-02-08 16:42 UTC, Deamon5550 commented on src/main/java/org/spongepowered/common/data/processor/multi/entity/AgeableDataProcessor.java
> +        } else /*if (entityCast instanceof EntityZombie)*/ { // commented so it doesn't throw an error
so initialize them? or throw an error in an else that the entity is unsupported.

2017-02-11 00:12 UTC, me4502 commented on src/main/java/org/spongepowered/common/data/processor/multi/entity/AgeableDataProcessor.java
> +        } else /*if (entityCast instanceof EntityZombie)*/ { // commented so it doesn't throw an error
With the current setup, if an unsupported entity was passed through for whatever reason, it'd be cast to EntityZombie. It'd be a much better to do what Deamon has suggested.

2017-04-13 08:02 UTC, gabizou requested changes
I would honestly ask for some short circuits on EntityAgeable and EntityZombie to eliminate uses of processors when able to do so.

2017-04-13 08:02 UTC, gabizou commented on src/main/java/org/spongepowered/common/data/manipulator/immutable/entity/ImmutableSpongeAgeableData.java
> +    private int age;
Field should be final.

2017-04-13 08:02 UTC, gabizou commented on src/main/java/org/spongepowered/common/data/processor/multi/entity/AgeableDataProcessor.java
> +            if (age != null) {
Still a question to this day... it should never be null, since the retrieval method is returning an integer and not an object.

2017-04-13 08:02 UTC, gabizou commented on src/main/java/org/spongepowered/common/data/processor/multi/entity/AgeableDataProcessor.java
> +        } else /*if (entityCast instanceof EntityZombie)*/ { // commented so it doesn't throw an error
This cannot be blindly casted. If you must cast between different entities, then perhaps you need multiple processors.

2017-04-13 08:02 UTC, gabizou commented on src/main/java/org/spongepowered/common/data/processor/value/entity/IsAdultValueProcessor.java
> +        if (container instanceof EntityAgeable) {
Likewise here, if you need to cast multiple times, might as well just have multiple processors.

2017-04-22 06:57 UTC, merged