Implemented MoveToBlock AI Task.
SpongePowered/Sponge pull request #1159
Opened 2017-01-25 12:37 UTC by me4502

[SpongeAPI ](https://github.com/SpongePowered/SpongeAPI/pull/1470) | SpongeCommon

This WIP PR is to add vanilla location-based AI tasks. The intention is to make it easier for plugins to control the movement of entities.

2017-01-27 07:08 UTC, liach requested changes

2017-01-27 07:08 UTC, liach commented on src/main/java/org/spongepowered/common/entity/ai/location/package-info.java
> +@org.spongepowered.api.util.annotation.NonnullByDefault package org.spongepowered.common.entity.ai.location;
Newline in the end please

2017-01-27 07:08 UTC, liach commented on src/main/java/org/spongepowered/common/mixin/core/entity/ai/MixinEntityAIMoveToBlock.java
> +}
line

2017-01-27 07:08 UTC, liach commented on src/main/java/org/spongepowered/common/entity/ai/location/SpongeMoveToBlockAIBuilder.java
> +}
line

2017-01-27 07:08 UTC, liach commented on src/main/java/org/spongepowered/common/mixin/core/entity/ai/MixinEntityAIMoveToBlock.java
> +    public double getSpeed() {
Should be mutable in API level

2017-01-27 07:08 UTC, liach commented on src/main/java/org/spongepowered/common/mixin/core/entity/ai/MixinEntityAIMoveToBlock.java
> +    public int getSearchRange() {
Should be mutable also

2017-01-27 07:08 UTC, liach commented on src/main/java/org/spongepowered/common/entity/ai/location/SpongeMoveToBlockAIBuilder.java
> +        return this.speed(value.getSpeed()).searchRange(value.getSearchRange());
`MoveToBlockAITask.builer().from(task).build()` will crash because of the absence of the predicate. Not so good...

2017-01-29 17:20 UTC, liach approved these changes

2017-01-29 18:28 UTC, liach commented on src/main/java/org/spongepowered/common/interfaces/ai/IMixinMoveToBlock.java
> +public interface IMixinMoveToBlock {
The name of this interface is a stub.

2017-01-29 18:28 UTC, liach commented on src/main/java/org/spongepowered/common/interfaces/ai/IMixinMoveToBlock.java
> +    boolean isVanillaTask();
Default it out to be true?

2017-01-30 16:15 UTC, liach commented
You need to fix your SpongeAPI submodule reference.

2017-02-21 04:27 UTC, liach requested changes

2017-02-21 04:27 UTC, liach commented on src/main/java/org/spongepowered/common/entity/ai/location/SpongeMoveToBlockAIBuilder.java
> +                return destinationPredicate.test(((World) worldIn).getLocation(pos.getX(), pos.getY(), pos.getZ()));
I think this code will make future change on the predicate for destination ineffective.

2017-02-21 04:55 UTC, me4502 commented on src/main/java/org/spongepowered/common/entity/ai/location/SpongeMoveToBlockAIBuilder.java
> +                return destinationPredicate.test(((World) worldIn).getLocation(pos.getX(), pos.getY(), pos.getZ()));
In what way?

2017-02-21 06:36 UTC, liach commented on src/main/java/org/spongepowered/common/entity/ai/location/SpongeMoveToBlockAIBuilder.java
> +                return destinationPredicate.test(((World) worldIn).getLocation(pos.getX(), pos.getY(), pos.getZ()));
The destinationPredicate seems to always refer to he one in the builder.

2017-02-21 06:38 UTC, me4502 commented on src/main/java/org/spongepowered/common/entity/ai/location/SpongeMoveToBlockAIBuilder.java
> +                return destinationPredicate.test(((World) worldIn).getLocation(pos.getX(), pos.getY(), pos.getZ()));
It wasn't intended to be changed, I've modified it though.

2017-02-21 06:53 UTC, kashike requested changes

2017-02-21 06:53 UTC, kashike commented on src/main/java/org/spongepowered/common/entity/ai/location/SpongeMoveToBlockAIBuilder.java
> +        this.reset();
useless

2017-02-21 07:44 UTC, liach approved these changes

2017-02-22 08:04 UTC, liach commented
@me4502 Should you fix the submodule reference?

2017-02-22 08:31 UTC, kashike commented on src/main/java/org/spongepowered/common/entity/ai/location/SpongeMoveToBlockAIBuilder.java
> +        if (!((IMixinEntityAIMoveToBlock) value).isVanillaTask()) {
Why?

2017-03-13 15:43 UTC, liach commented on src/main/java/org/spongepowered/common/entity/ai/location/SpongeMoveToBlockAIBuilder.java
> +        if (!((IMixinEntityAIMoveToBlock) value).isVanillaTask()) {
Because the vanilla task does not use a predicate.

2017-06-19 06:02 UTC, liach commented on src/main/java/org/spongepowered/common/mixin/core/entity/ai/MixinEntityAIMoveToBlock.java
> +}
line

2017-06-19 06:08 UTC, me4502 commented on src/main/java/org/spongepowered/common/mixin/core/entity/ai/MixinEntityAIMoveToBlock.java
> +}
So on my local machine there's a line there - not sure why it isn't there on github. I'll look into it.

2018-08-28 20:21 UTC, ImMorpheus commented
@me4502 Status ? Is this ready for review ?

2018-08-29 02:31 UTC, me4502 commented
@ImMorpheus Yeah, I think Zidane wanted to work out what was happening regarding AI first, but that was ages ago so I’m not sure what’s happening

2019-05-04 19:56 UTC, ImMorpheus commented
https://github.com/SpongePowered/SpongeAPI/pull/1470#issuecomment-489360563

2019-05-04 19:56 UTC, closed without merging