[WIP] Implement IgniteEntityEvent
SpongePowered/Sponge pull request #1170
Opened 2017-01-29 00:00 UTC by Maxqia

2017-01-29 02:41 UTC, gabizou requested changes
A little sloppy. You provide no real explanation as to what you're aiming to do here. PR has no description.

2017-01-29 02:41 UTC, gabizou commented on src/main/java/org/spongepowered/common/mixin/core/entity/MixinEntity.java
> +    @Nullable private DamageSource originalLava, originalFire, originalLightning;
Make these individual fields. Don't take syntactical shortcuts like this.

2017-01-29 02:41 UTC, gabizou commented on src/main/java/org/spongepowered/common/mixin/core/entity/MixinEntity.java
> -    private static final String ATTACK_ENTITY_FROM_METHOD = "Lnet/minecraft/entity/Entity;attackEntityFrom(Lnet/minecraft/util/DamageSource;F)Z";
Line noise. don't move static fields around in this case.

2017-01-29 02:41 UTC, gabizou commented on src/main/java/org/spongepowered/common/mixin/core/entity/MixinEntity.java
> +     * Overwritten due to pass-by-value nature of Java
Explains nothing to anyone. Why was this overwritten.

2017-01-29 02:41 UTC, gabizou commented on src/main/java/org/spongepowered/common/mixin/core/entity/MixinEntity.java
> +            PhaseContext context = ((IMixinWorldServer) world).getCauseTracker().getCurrentContext();
What are the comments for saying "Here is where sponge is making a change.... This other part is vanilla code."

Look at other examples of overwrites (MixinWorld or MixinChunk even).

2017-01-29 02:41 UTC, gabizou commented on src/main/java/org/spongepowered/common/mixin/core/entity/MixinEntity.java
> +            ((IMixinWorldServer) world).getCauseTracker().getCurrentContext().add(NamedCause.of(NamedCause.SOURCE, source));
Why?

2017-01-29 02:41 UTC, gabizou commented on src/main/java/org/spongepowered/common/mixin/core/entity/MixinEntity.java
> +            DamageSource.IN_FIRE = new EntityDamageSource("lightningBolt", lightningBolt);
Uh, what?

2017-01-29 05:48 UTC, liach commented on src/main/java/org/spongepowered/common/mixin/core/entity/MixinEntity.java
> +                Thread.dumpStack();
Is this test code?

2017-01-29 06:10 UTC, Maxqia commented on src/main/java/org/spongepowered/common/mixin/core/entity/MixinEntity.java
> +                Thread.dumpStack();
This was mostly inspired by postDealFireDamage/postSetOnFire, which includes that for some reason.

2017-01-29 06:12 UTC, Maxqia commented on src/main/java/org/spongepowered/common/mixin/core/entity/MixinEntity.java
> +            ((IMixinWorldServer) world).getCauseTracker().getCurrentContext().add(NamedCause.of(NamedCause.SOURCE, source));
Needed context for setFire and this is always called before it.

2017-01-29 06:14 UTC, Maxqia commented on src/main/java/org/spongepowered/common/mixin/core/entity/MixinEntity.java
> +            DamageSource.IN_FIRE = new EntityDamageSource("lightningBolt", lightningBolt);
Mainly did this to pass the entity (the lightning bolt) through as a source, which has a representation in Sponge.

2017-01-29 06:40 UTC, liach commented on src/main/java/org/spongepowered/common/mixin/core/entity/MixinEntity.java
> +            DamageSource.IN_FIRE = new EntityDamageSource("lightningBolt", lightningBolt);
Seems you never set this back.

2017-01-29 06:49 UTC, liach commented on src/main/java/org/spongepowered/common/mixin/core/entity/MixinEntity.java
> +                Thread.dumpStack();
You can probably just make a throwable, I think.

2017-01-29 07:44 UTC, Maxqia commented on src/main/java/org/spongepowered/common/mixin/core/entity/MixinEntity.java
> +            DamageSource.IN_FIRE = new EntityDamageSource("lightningBolt", lightningBolt);
0-0 wait wat, that's the wrong field!

2017-01-29 07:56 UTC, liach commented on src/main/java/org/spongepowered/common/mixin/core/entity/MixinEntity.java
> +            DamageSource.IN_FIRE = new EntityDamageSource("lightningBolt", lightningBolt);
😆

2018-01-01 09:38 UTC, Meronat commented
@Maxqia Do you plan to update this?

2018-01-01 19:37 UTC, liach commented
I don't think he's active.

2018-01-02 08:08 UTC, gabizou commented
Pending 14 days from today, this PR is going to be closed for being stale, no development has been made.

2018-01-18 00:38 UTC, Meronat commented
Going to close this due to inactivity, thanks for your contribution though!

Has also been superseded by https://github.com/SpongePowered/SpongeCommon/pull/1708

2018-01-18 00:38 UTC, closed without merging