Absorption data
SpongePowered/Sponge pull request #1182
Opened 2017-02-02 10:14 UTC by kashike

[SpongeAPI](https://github.com/SpongePowered/SpongeAPI/pull/1476) | [**SpongeCommon**](https://github.com/SpongePowered/SpongeCommon/pull/1182)

2017-02-19 18:02 UTC, gabizou approved these changes
Good stuff.

2017-02-25 07:15 UTC, gabizou requested changes
Minor caching change. Need to have a test plugin to double check will work on players.

2017-02-25 07:15 UTC, gabizou commented on src/main/java/org/spongepowered/common/data/manipulator/immutable/entity/ImmutableSpongeAbsorptionData.java
> +        return new ImmutableSpongeValue<>(this.usedKey, DataConstants.Entity.DEFAULT_ABSORPTION, this.getValue());
Should be cached.

2017-04-13 07:49 UTC, Minecrell commented
@gabizou Test plugin is in the API PR.

2017-04-18 02:25 UTC, merged