Implement Container methods
SpongePowered/Sponge pull request #1209
Opened 2017-02-15 20:34 UTC by Limeth

2017-02-16 00:02 UTC, kashike requested changes

2017-02-16 00:02 UTC, kashike commented on src/main/java/org/spongepowered/common/mixin/core/entity/player/MixinEntityPlayerMP.java
> +        if (openContainer != inventoryContainer) {
`this.`

2017-02-16 00:02 UTC, kashike commented on src/main/java/org/spongepowered/common/mixin/core/entity/player/MixinEntityPlayerMP.java
> +        IMixinContainer mixinContainer = (IMixinContainer) openContainer;
`this.`

2017-02-16 00:02 UTC, kashike commented on src/main/java/org/spongepowered/common/mixin/core/item/inventory/MixinContainer.java
> +        return playerList.size() > 0;
`this.`

2017-02-16 00:02 UTC, kashike commented on src/main/java/org/spongepowered/common/mixin/core/item/inventory/MixinContainer.java
> +        return ImmutableSet.copyOf((Set) playerList);
`this.`

2017-02-16 10:42 UTC, kashike requested changes

2017-02-16 10:42 UTC, kashike commented on src/main/java/org/spongepowered/common/mixin/core/entity/player/MixinEntityPlayerMP.java
> +        this.openContainer.addListener(this$);
`this.this$`

2017-02-16 10:50 UTC, Limeth commented on src/main/java/org/spongepowered/common/mixin/core/entity/player/MixinEntityPlayerMP.java
> +        this.openContainer.addListener(this$);
I wasn't sure about that one. :smile:

2018-01-18 00:37 UTC, Meronat commented
Going to close this due to inactivity, if you'd still like to get this in, update for the latest changes and open a new pull request.

Thanks for your contribution!

2018-01-18 00:37 UTC, closed without merging