GuiIDProperty and ContainerProvider Impl.
SpongePowered/Sponge pull request #1221
Opened 2017-02-26 07:34 UTC by Faithcaio

[API](https://github.com/SpongePowered/SpongeAPI/pull) | [Common](https://github.com/SpongePowered/SpongeCommon/pull/)

2017-02-26 08:18 UTC, kashike requested changes

2017-02-26 08:18 UTC, kashike commented on src/main/java/org/spongepowered/common/item/inventory/custom/CustomInventory.java
> +        return archetype.getProperty(GuiIDProperty.class, GuiIDProperty.class.getSimpleName().toLowerCase()).map(p -> p.getValue()).orElse("minecraft:chest");
`this.`

2017-02-26 08:18 UTC, kashike commented on src/main/java/org/spongepowered/common/item/inventory/archetype/CompositeInventoryArchetype.java
> +        {
Brace is on the wrong line.

2017-02-27 01:49 UTC, liach commented on src/main/java/org/spongepowered/common/item/inventory/archetype/CompositeInventoryArchetype.java
> +            BiFunction<Inventory, Player, Container> containerProvider) {
`@Nullable`

2017-02-27 05:59 UTC, kashike requested changes

2017-02-27 05:59 UTC, kashike commented on src/main/java/org/spongepowered/common/item/inventory/archetype/CompositeInventoryArchetype.java
> +        if (containerProvider == null) {
`this.`

2017-02-27 05:59 UTC, kashike commented on src/main/java/org/spongepowered/common/item/inventory/archetype/CompositeInventoryArchetype.java
> +        return containerProvider.apply(inventory, player);
`this.`

2017-02-27 05:59 UTC, kashike commented on src/main/java/org/spongepowered/common/item/inventory/archetype/SpongeInventoryArchetypeBuilder.java
> +        return new CompositeInventoryArchetype(id, name, types, properties, containerProvider);
`this.`

2017-02-27 05:59 UTC, kashike commented on src/main/java/org/spongepowered/common/item/inventory/custom/CustomInventory.java
> +                ("minecraft:chest");
This formatting is weird - you should move the entire call (`.orElse("minecraft:chest");` to this line, or move this to the previous line.

2017-02-28 13:40 UTC, Faithcaio commented on src/main/java/org/spongepowered/common/item/inventory/custom/CustomInventory.java
> +                ("minecraft:chest");
damn autoformatting

2017-07-26 11:43 UTC, kashike requested changes

2017-07-26 11:43 UTC, kashike commented on src/main/java/org/spongepowered/common/item/inventory/custom/CustomInventory.java
> +        return this.archetype.getProperty(GuiIdProperty.class, GuiIdProperty.class.getSimpleName().toLowerCase()).map(p -> p.getValue()).orElse
Worth caching the value of `GuiIdProperty.class.getSimpleName().toLowerCase()`?

2017-07-26 11:43 UTC, kashike commented on src/main/java/org/spongepowered/common/mixin/core/item/inventory/MixinContainerHorseChest.java
> +        return Optional.empty(); // TODO can we get the horse in here somehow?
Could, technically, throw a mixin into `net.minecraft.entity.passive.AbstractHorse#initHorseChest` to set the carrier?

2017-07-26 11:43 UTC, kashike commented on src/main/java/org/spongepowered/common/mixin/core/item/inventory/MixinContainerHorseChest.java
> +package org.spongepowered.common.mixin.core.item.inventory;
Missing license header.

2017-08-11 21:04 UTC, kashike requested changes

2017-08-11 21:04 UTC, kashike commented on src/main/java/org/spongepowered/common/item/inventory/archetype/CompositeInventoryArchetype.java
> +    private ContainerProvider containerProvider;
`@Nullable`

2017-08-11 21:04 UTC, kashike commented on src/main/java/org/spongepowered/common/item/inventory/archetype/CompositeInventoryArchetype.java
> +    public ContainerProvider getContainerProvider() {
`@Nullable`

2017-08-11 21:04 UTC, kashike commented on src/main/java/org/spongepowered/common/registry/type/item/GuiIdRegistryModule.java
> +}
newline

2017-08-19 22:23 UTC, merged