MixinICommandSender: Don't call asICommandSource() when no one implements it.
SpongePowered/Sponge pull request #1247
Opened 2017-03-11 13:19 UTC by JBYoshi

Fixes SpongePowered/SpongeForge#1333.

2017-03-12 16:11 UTC, stephan-gh requested changes

2017-03-12 16:11 UTC, Minecrell commented on src/main/java/org/spongepowered/common/mixin/core/command/MixinICommandSender.java
> +    public void onCanUseCommand(int permissionLevel, String commandName, CallbackInfoReturnable<Boolean> cir) {
Injection can be private

2017-03-26 01:09 UTC, JBYoshi commented on src/main/java/org/spongepowered/common/mixin/core/command/MixinICommandSender.java
> +    public void onCanUseCommand(int permissionLevel, String commandName, CallbackInfoReturnable<Boolean> cir) {
@Minecrell Fixed.

2017-05-08 11:28 UTC, JBYoshi commented
Not sure why I closed that before it was merged. I will reopen/remake this later today; ping me if I forget.

2017-05-08 17:20 UTC, JBYoshi commented
Reopened. I will need to make a few changes, though.

2017-07-11 13:45 UTC, JBYoshi commented
Merged in https://github.com/SpongePowered/SpongeCommon/commit/2342f2f7411210dbd4fa6489b8ce71544277adf6.

2017-07-11 13:45 UTC, closed without merging