Fix All CatalogType Registry Modules
SpongePowered/Sponge pull request #1257
Opened 2017-03-16 20:45 UTC by gabizou

This goes through and fixes all existing `CatalogType` `RegistryModule`s with some new unit testing.

Some tests that are added:
- Check all CatalogType fields are successfully registered (new PR's adding new catalog types will have to pass this test)
- Check all CatalogType fields can be retrieved from their designated registry modules
- Check all Registries can successfully retrieve all collected values
- Check all Registries contains all registered catalogs

Some things to add in the future:

- Alias registration - The ability to register custom aliases for certain types, be it an improved name, or differing legacy id
- Assurance that all id's are properly formatted, not just the names themselves.

I'm open for discussion.

2017-03-16 20:59 UTC, Deamon5550 requested changes

2017-03-16 20:59 UTC, Deamon5550 commented on src/main/java/org/spongepowered/common/registry/SpongeGameRegistry.java
> +        final PrettyPrinter printer = new PrettyPrinter(100).add("Printing all Catalogs and their ID's").centre().hr()
Left in debug? Could always leave it and put it behind a system property.

2017-03-16 20:59 UTC, Deamon5550 commented on src/main/java/org/spongepowered/common/registry/type/ItemTypeRegistryModule.java
> +            id = "minecraft:" + id.toLowerCase(); // assume vanilla
need to pass `Locale.ENGLISH` here don't you?

2017-03-16 20:59 UTC, Deamon5550 commented on src/main/java/org/spongepowered/common/registry/type/block/SlabTypeRegistryModule.java
> +                id -> id.equals("nether_brick")
ಠ_ಠ

2017-03-18 11:40 UTC, ST-DDT commented on src/main/java/org/spongepowered/common/data/type/SpongeSpawnType.java
> +        return super.getName();
Why do we return the parents name instead of the name we store a few lines above?

2017-03-18 11:40 UTC, ST-DDT commented on src/main/java/org/spongepowered/common/mixin/core/data/types/MixinBlockSlabEnumBlockHalf.java
> +        return "minecraft:" + getName();
Why didnt you prefix this with shadow like you did everywhere else?

2017-03-18 11:40 UTC, ST-DDT commented on src/main/java/org/spongepowered/common/mixin/core/world/MixinWorldType.java
> +
Too much whitespace.

2017-03-18 11:40 UTC, ST-DDT commented on src/main/java/org/spongepowered/common/registry/CatalogTypeRequiresVerification.java
> +public @interface CatalogTypeRequiresVerification {
Missing javdadoc

2017-03-18 21:29 UTC, Meronat commented on src/test/java/org/spongepowered/common/registry/CatalogTypeClassesTest.java
> +package org.spongepowered.common.registry;
Missing license.

2017-03-18 22:14 UTC, kashike commented on src/main/java/org/spongepowered/common/data/manipulator/immutable/entity/ImmutableSpongeSkeletonData.java
> +        org.spongepowered.api.data.manipulator.immutable.entity.ImmutableSkeletonData,
What's with the fully-qualified names?

2017-03-23 06:47 UTC, merged