Fixhelp
SpongePowered/Sponge pull request #1305
Opened 2017-04-14 08:44 UTC by ryantheleach

Requires: https://github.com/SpongePowered/SpongeAPI/pull/1539

Alternative to: https://github.com/SpongePowered/SpongeCommon/pull/1303

/page is still preferable to /help as /help reconstructs the entire pagination each time. 

/help 2 however will still continue to work even after the pagination expires.

I've also added the default minecraft help tip to the text, and changed the header to more closely match the default minecraft header.

![image](https://cloud.githubusercontent.com/assets/141554/25038417/e59b7e18-213d-11e7-97c2-72af93f126ad.png)

![image](https://cloud.githubusercontent.com/assets/141554/25038428/f2c90006-213d-11e7-9ef4-a284fe61b668.png)

![image](https://cloud.githubusercontent.com/assets/141554/25038435/fb648d20-213d-11e7-932c-70f2638d2b76.png)

Only current downside, is that the error handling slightly pollutes the usage text for /help.

![image](https://cloud.githubusercontent.com/assets/141554/25038473/278b861a-213e-11e7-8f05-26e12692e562.png)

2017-04-24 19:14 UTC, kashike requested changes

2017-04-24 19:14 UTC, kashike commented on src/main/java/org/spongepowered/common/command/SpongeHelpCommand.java
> +    private static final Text pageKey = Text.of("page");
`PAGE_KEY`

2017-04-24 19:14 UTC, kashike commented on src/main/java/org/spongepowered/common/command/SpongeHelpCommand.java
> +    private static final Text commandKey = Text.of("command");
`COMMAND_KEY`

2017-04-24 19:14 UTC, kashike commented on src/main/java/org/spongepowered/common/command/SpongeHelpCommand.java
> +    private static final Text notFound = Text.of("notFound");
`NOT_FOUND`

2017-04-24 19:14 UTC, kashike commented on src/main/java/org/spongepowered/common/command/SpongeHelpCommand.java
> +    private static final CommandElement commandArgument = new CommandElement(commandKey){
`COMMAND_ARGUMENT`

2017-06-11 10:51 UTC, kashike commented on src/main/java/org/spongepowered/common/command/SpongeHelpCommand.java
> +    private static final CommandElement COMMAND_ARGUMENT = new CommandElement(COMMAND_KEY){
`) {`

2017-08-16 14:49 UTC, Zidane commented
@ryantheleach 

Is this still needed? If so, get this rebased on latest bleeding please.

2017-08-18 00:26 UTC, ryantheleach commented
https://github.com/SpongePowered/SpongeCommon/pull/1475 covered adding the methods needed, but this still has changes to the HelpCommand itself.

Seems like a small task to fix it and get ready, I'll get this done tonight.

2017-08-18 12:10 UTC, ryantheleach commented
Apologies for the API Bump/Revert API Bump, was having a little trouble with the rebase.

2017-08-18 14:21 UTC, Zidane commented
@ryantheleach 

Do NOT separate the Help command back into its own class. That was merged in Grinch's PR for the plugins command changes due to my specific instructions.

2017-08-18 15:10 UTC, ryantheleach commented on src/main/java/org/spongepowered/common/command/SpongeCommandGenerator.java
> +                .builder()
Is this whitespace weird? I notice it differs from grinches.

2017-08-18 21:05 UTC, kashike commented on src/main/java/org/spongepowered/common/command/SpongeCommandGenerator.java
> +public class SpongeCommandGenerator {
Why the rename?

2017-08-18 21:10 UTC, Meronat commented on src/main/java/org/spongepowered/common/command/SpongeCommandGenerator.java
> +public class SpongeCommandGenerator {
I think Zidane wanted this.

2017-08-18 21:13 UTC, kashike commented on src/main/java/org/spongepowered/common/command/SpongeCommandGenerator.java
> +public class SpongeCommandGenerator {
I see no comment about it.

2017-08-18 21:23 UTC, kashike commented on src/main/java/org/spongepowered/common/command/SpongeCommandGenerator.java
> +public class SpongeCommandGenerator {
Use `SpongeCommandFactory` instead.

2017-09-24 17:55 UTC, kashike commented
Could you please update this pull request, @ryantheleach?

2017-10-12 03:08 UTC, Meronat commented
Should be good for a final review @kashike along with it's Forge PR: https://github.com/SpongePowered/SpongeForge/pull/1734

2017-10-12 04:04 UTC, kashike approved these changes

2017-10-12 04:07 UTC, merged