Implement Inventory.getPlugin(), pretty much everywhere.
SpongePowered/Sponge pull request #1357
Opened 2017-05-17 13:53 UTC by JBYoshi

**SpongeCommon** | SpongeForge

Fixes SpongePowered/SpongeCommon#1222.

2017-05-18 14:35 UTC, Zidane commented on src/main/java/org/spongepowered/common/mixin/core/item/inventory/TraitInventoryAdapter.java
> +            return SpongeImpl.getMinecraftPlugin();
I wonder if this should be the SpongeAPI plugin instead..

2017-05-19 08:01 UTC, kashike requested changes

2017-05-19 08:01 UTC, kashike commented on src/main/java/org/spongepowered/common/item/inventory/EmptyInventoryImpl.java
> +        return parent.getPlugin();
`this.`

2017-05-19 14:18 UTC, JBYoshi commented on src/main/java/org/spongepowered/common/mixin/core/item/inventory/TraitInventoryAdapter.java
> +            return SpongeImpl.getMinecraftPlugin();
I decided to use the Minecraft plugin for consistency with the `Player` inventory; they're conceptually the same, so IMO they should have the same owner. I'm open to changing it, however.

2017-08-06 02:36 UTC, JBYoshi commented
Can this be merged?

2017-08-06 05:54 UTC, Faithcaio commented
Can you add testplugin?

2017-08-06 05:57 UTC, Zidane commented on src/main/java/org/spongepowered/common/mixin/core/item/inventory/TraitInventoryAdapter.java
> +        SpongeImpl.getLogger().warn("Unknown plugin for " + this);
Can you finish this TODO?

2017-08-06 05:58 UTC, Zidane commented on src/main/java/org/spongepowered/common/mixin/core/item/inventory/TraitInventoryAdapter.java
> +            String id = ((TileEntity) this).getBlock().getType().getId();
I concur with @Faithcaio about the testing plugin for this part alone.

2017-08-10 03:26 UTC, JBYoshi commented
@Zidane I finished up the TODO.

@Faithcaio I got the test plugin ready. Just open and close any inventory and you should see the credits pop up. (And by credits I mean the name of the plugin that created the inventory. :wink:)

2017-08-10 22:19 UTC, Meronat commented
You are missing the license on the test plugin, but otherwise looks good.

2017-08-11 12:42 UTC, JBYoshi commented
*facepalm*
Time to rework my Git hooks...

2017-08-11 13:45 UTC, Zidane commented
@JBYoshi 

No worries, I can take care of the license when I pull.

2017-08-11 15:57 UTC, Zidane commented
Merged in: https://github.com/SpongePowered/SpongeCommon/commit/4f6471aae9b031835bb16706a38ca9dcd30e6091

2017-08-11 15:57 UTC, closed without merging