[WIPRework some of the SpongeTeleportHelper
SpongePowered/Sponge pull request #1362
Opened 2017-05-20 16:39 UTC by dualspiral

**Sponge API** | SpongeCommon | [Original Issue](https://github.com/SpongePowered/SpongeCommon/issues/848)

2017-05-20 22:34 UTC, kashike requested changes

2017-05-20 22:34 UTC, kashike commented on src/main/java/org/spongepowered/common/registry/type/world/TeleportHelperKernelRegistryModule.java
> +    @Override public Optional<TeleportHelperKernel> getById(String id) {
Annotation should be on it's own line.
```java
    @Override
    public Optional...
```

2017-05-20 22:34 UTC, kashike commented on src/main/java/org/spongepowered/common/world/teleport/DefaultTeleportHelperKernel.java
> +        Material.AIR, Material.PLANTS, Material.WATER, Material.REDSTONE_LIGHT, Material.CIRCUITS, Material.SNOW, Material.PORTAL, Material.WEB,
Wrong indentation.

2017-05-20 22:34 UTC, kashike commented on src/main/java/org/spongepowered/common/world/teleport/DefaultTeleportHelperKernel.java
> +    @Override public String getId() {
Annotation should be on it's own line.
```java
    @Override
    public String...
```

2017-05-22 23:44 UTC, kashike requested changes

2017-05-22 23:44 UTC, kashike commented on src/main/java/org/spongepowered/common/registry/type/world/TeleportHelperKernelRegistryModule.java
> +    private final Map<String, TeleportHelperFilter> kernelMap = Maps.newHashMap();
Should be renamed to match the new name of the interface.

2017-05-22 23:44 UTC, kashike commented on src/main/java/org/spongepowered/common/registry/type/world/TeleportHelperKernelRegistryModule.java
> +        return Optional.ofNullable(this.idMap.get(id));
`id` should be `toLowerCase(Locale.ENGLISH)`'d

2017-05-25 19:44 UTC, dualspiral commented
I've added support for a configurable blacklist of blocks, so that behaviour of the helper can be altered via the global config.

There are a few things to note with how I've done this:

* I've written the block blacklist in the config module to accept both `BlockType` and `BlockState` ids. My reasoning is that you might want to block `minecraft:stained_glass` from being a target no matter what state it's in, and not have to list all its states (colours in this case).
* To prevent potentially expensive lookup operations each time, I cache the `BlockType`s and `BlockState`s, and invalidate the list when the config is reloaded - [it gets invalidated here](https://github.com/SpongePowered/SpongeCommon/pull/1362/files#diff-6bdb73ca8e3f612a09b73db110192b5cR523).
* The config blacklist works with all Sponge (i.e. this PR) provided filters, but a plugin provided filter doesn't necessarily use the block (it's always available as a separate filter, `TeleportHelperFilters.CONFIG`). However, I'm considering making it a mandatory filter completely backed into the helper, because I feel like a plugin probably shouldn't override a user. Thoughts?

2017-05-30 04:41 UTC, ryantheleach commented
In general "I feel like a plugin probably shouldn't override a user." 

I feel like this statement should be used as a default, i.e. user choices in configs in sponge should be applied by default, but have a method to avoid them if it directly conflicts with a plugins own configs / intentions.

In this specific case I'm not sure it matters one way or another, considering it's a safe teleporter.

2017-06-06 20:34 UTC, dualspiral commented
So, what I've opted to do is add an option to make the blacklist mandatory in the config (which adds the `CONFIG` filter to the set of filters _always_). 

I have also added a method in the API to use the blacklist (mostly as a convenience function) that adds the blacklist (`CONFIG`) filter automatically regardless of whether the blacklist is forced or not, just to give the blacklist filter more visbility (plugins might be more inclined to use a method that specifies the blacklist, rather than a different filter).

This should give plugins the flexibilty of deciding whether to use this blacklist or not, and users the ability to override this if they feel like they need to.

2017-08-10 21:00 UTC, Zidane commented
Merged in https://github.com/SpongePowered/SpongeCommon/commit/5a35b18813d49d583c53a9eb2afcf2e30663eb36

2017-08-10 21:00 UTC, closed without merging