Implement Recipe API
SpongePowered/Sponge pull request #1395
Opened 2017-06-15 08:42 UTC by Faithcaio

[SpongeAPI](https://github.com/SpongePowered/SpongeAPI/pull/1582)|*SpongeCommon*|[SpongeForge TODO]()

TODO

2017-06-15 14:26 UTC, kashike requested changes

2017-06-15 14:26 UTC, kashike commented on src/main/java/org/spongepowered/common/item/recipe/crafting/CustomIngredient.java
> +        if (predicates.stream().anyMatch(p -> p.test(ItemStackUtil.fromNative(p_apply_1_)))) {
`this.`

2017-06-15 14:26 UTC, kashike commented on src/main/java/org/spongepowered/common/item/recipe/crafting/CustomIngredient.java
> +    public boolean apply(@Nullable net.minecraft.item.ItemStack p_apply_1_) {
parameter could use a better name.

2017-06-15 14:26 UTC, kashike commented on src/main/java/org/spongepowered/common/item/recipe/crafting/DelegateIngredient.java
> +    public boolean apply(@Nullable ItemStack p_apply_1_) {
parameter could use a better name

2017-06-15 14:26 UTC, kashike commented on src/main/java/org/spongepowered/common/item/recipe/crafting/DelegateIngredient.java
> +        return delegate.test(ItemStackUtil.fromNative(p_apply_1_));
`this.`

2017-06-15 14:26 UTC, kashike commented on src/main/java/org/spongepowered/common/item/recipe/crafting/SpongeCraftingRecipeRegistry.java
> +        return Streams.stream(CraftingManager.REGISTRY.iterator()).map(CraftingRecipe.class::cast).collect(Collectors.toList());
`.collect(ImmutableList.toImmutableList())`

2017-06-15 21:19 UTC, liach commented on src/main/java/org/spongepowered/common/item/recipe/crafting/SpongeShapedCraftingRecipeBuilder.java
> +        this.groupName = name == null ? "" : name;
Use `Strings.nullToEmpty`

2017-06-15 21:19 UTC, liach commented on src/main/java/org/spongepowered/common/mixin/core/item/inventory/MixinContainer.java
> +        throw new IllegalStateException("Shadowed.");
Why not making this abstract?

2017-06-15 21:19 UTC, liach commented on src/main/java/org/spongepowered/common/registry/SpongeGameRegistry.java
> +        return new SpongeCraftingRecipeRegistry(); // TODO cache it somewhere
Cache it in `SpongeCraftingRecipeRegistry`?

2017-06-15 21:19 UTC, liach commented on src/main/resources/META-INF/common_at.cfg
> +public net.minecraft.entity.EntityList func_191303_a(ILjava/lang/String;Ljava/lang/Class;Ljava/lang/String;)V # register
Are these intentional?

2017-06-15 21:27 UTC, Faithcaio commented on src/main/java/org/spongepowered/common/mixin/core/item/inventory/MixinContainer.java
> +        throw new IllegalStateException("Shadowed.");
MixinContainerCrafting extends this and calls super.slotClick

2017-06-15 21:28 UTC, Faithcaio commented on src/main/resources/META-INF/common_at.cfg
> +public net.minecraft.entity.EntityList func_191303_a(ILjava/lang/String;Ljava/lang/Class;Ljava/lang/String;)V # register
must have happened when rebasing stuff

2017-06-15 21:31 UTC, liach commented on src/main/java/org/spongepowered/common/mixin/core/item/inventory/MixinContainer.java
> +        throw new IllegalStateException("Shadowed.");
Oh, one of the rare cases!

2017-06-15 21:51 UTC, liach commented on src/main/java/org/spongepowered/common/item/recipe/crafting/SpongeCraftingRecipeRegistry.java
> +import com.google.inject.Singleton;
Do you want this annotation?

2017-06-15 21:52 UTC, Faithcaio commented on src/main/java/org/spongepowered/common/item/recipe/crafting/SpongeCraftingRecipeRegistry.java
> +import com.google.inject.Singleton;
nobody can know!

2017-06-15 21:54 UTC, liach approved these changes

2017-06-18 10:22 UTC, stephan-gh requested changes

2017-06-18 10:22 UTC, Minecrell commented on src/main/java/org/spongepowered/common/mixin/core/item/recipe/smelting/MixinFurnaceRecipes.java
> +    public void onGetSmeltingResult(ItemStack stack, CallbackInfoReturnable<ItemStack> cir) {
There is no need to have this public

2017-06-18 10:22 UTC, Minecrell commented on src/main/java/org/spongepowered/common/mixin/core/item/recipe/smelting/MixinFurnaceRecipes.java
> +    public void onGetSmeltingExperience(ItemStack stack, CallbackInfoReturnable<Float> cir) {
There is no need to have this public

2017-06-18 19:01 UTC, Faithcaio commented
https://github.com/SpongePowered/SpongeCommon/commit/2a7a3664f2acbb92c1a5750ad288b1e242986e58

2017-06-18 19:01 UTC, closed without merging