Implement new high-level command API
SpongePowered/Sponge pull request #1400
Opened 2017-06-18 19:57 UTC by dualspiral

[Sponge API](https://github.com/SpongePowered/SpongeAPI/pull/1587) | **SpongeCommon**

Note that this is nowhere near completion, and won't yet work. For more discussion, please see the API PR.

2017-06-30 08:50 UTC, michaelzangl commented
Just if you need it: For Minebot I needed a lot of [commands](https://github.com/michaelzangl/minebot/tree/forge-1.12/Minebot/src/net/famzangl/minecraft/minebot/ai/commands). This is why I wrote my own [command parser](https://github.com/michaelzangl/minebot/tree/forge-1.12/Minebot/src/net/famzangl/minecraft/minebot/ai/command). Parsing is done by the `CommandDefinition` class. Commands can simply be defined in a class:

	@AICommand(name = "minebuild", helpText = "Fill an area with a given block.")
	public class CommandFillArea {
		public static AIStrategy run(
			AIHelper helper,
			@AICommandParameter(type = ParameterType.FIXED, fixedName = "fill", description = "") String nameArg,
			@AICommandParameter(type = ParameterType.BLOCK_NAME, blockFilter=FillAreaPathfinder.FillBlocks.class, description = "The block to place") BlockWithDataOrDontcare block) {
			...
		}
	}

This automatically adds the help text for the command with the parameter description. Tab complete is fully supported. Parameter types can be blocks, enums, strings, numbers, BlockPos. It is could be made easy to add a new parameter type by using a class instead of an enum constant.
Command invocations are then:
`/minebuild fill stone`

(currently licensed under GPL, but I have no problem with re-licensing my parts under MIT)

2017-07-09 05:25 UTC, gabizou commented
If you can, when you update the implementation with bleeding, provide a test plugin to make some examples of how things would look with the API changes. I think it would suit better with the description overall.

2017-07-09 07:32 UTC, dualspiral commented
Okie doke, will do.

2017-07-25 07:06 UTC, ryantheleach commented
This enables https://github.com/SpongePowered/SpongeCommon/issues/1463 right?

2017-07-25 07:54 UTC, dualspiral commented
Yes.

2017-07-25 07:56 UTC, Meronat commented
@dualspiral Making all of our dreams come true.

2017-07-25 07:56 UTC, zml2008 commented
it's finally happening!

2017-07-25 20:57 UTC, kashike requested changes

2017-07-25 20:57 UTC, kashike commented on src/main/java/co/aikar/timings/TimingsExport.java
> +                .add("setFlags", RUNTIME_FLAG_JOINER.join(runtimeBean.getInputArguments()))
no

2017-07-25 20:57 UTC, kashike commented on src/main/java/org/spongepowered/common/command/parameter/flag/SpongeFlags.java
> +            return createError(t("Short setFlags that are not at the end of a group cannot have a value."));
Should probably be flags, not setFlags

2017-07-26 13:21 UTC, dualspiral commented on src/main/java/org/spongepowered/common/command/parameter/flag/SpongeFlags.java
> +            return createError(t("Short setFlags that are not at the end of a group cannot have a value."));
I'll get this right one day...

2019-02-02 15:37 UTC, dualspiral commented
Closed in favour of https://github.com/SpongePowered/SpongeAPI/pull/1958 for 1.13

2019-02-02 15:37 UTC, closed without merging