Implement Inventory Transfer Events
SpongePowered/Sponge pull request #1410
Opened 2017-06-25 17:02 UTC by Faithcaio

[SpongeAPI](https://github.com/SpongePowered/SpongeAPI/pull/1591) | *SpongeCommon* | SpongeForge | [Issue](https://github.com/SpongePowered/SpongeCommon/issues/1402)

2017-07-22 13:42 UTC, kashike commented on src/main/java/org/spongepowered/common/item/inventory/util/EventUtil.java
> +public final class EventUtil {
`InventoryEventUtil` might be a better name for this.

2017-07-22 21:34 UTC, kashike commented on src/main/java/org/spongepowered/common/item/inventory/util/InventoryUtil.java
> +        for (EnumFacing enumfacing : EnumFacing.Plane.HORIZONTAL) {
variables in here could use nicer names

2017-07-22 21:34 UTC, kashike commented on src/main/java/org/spongepowered/common/item/inventory/util/InventoryUtil.java
> +                {
formatting

2017-07-22 21:43 UTC, Faithcaio commented on src/main/java/org/spongepowered/common/item/inventory/util/InventoryUtil.java
> +        for (EnumFacing enumfacing : EnumFacing.Plane.HORIZONTAL) {
this is from a copy BlockChest#getContainer

2017-07-25 16:27 UTC, gabizou requested changes

2017-07-25 16:27 UTC, gabizou commented on src/main/java/org/spongepowered/common/item/inventory/util/EventUtil.java
> +public final class EventUtil {
Or stick it in `InventoryUtil`...

2017-07-25 16:27 UTC, gabizou commented on src/main/java/org/spongepowered/common/item/inventory/util/EventUtil.java
> +        Cause.Builder builder = Cause.source(source);
Short of the notifiers and owners of the `TileEntity`, what is activating the transfer? Is the destination always an inventory? Is it contained by a carrier? Is it the `TileEntity` that is performing the operation? Can't we use the `CauseTracker` to preview what sort of sources are available?

2017-07-25 16:27 UTC, gabizou commented on src/main/java/org/spongepowered/common/item/inventory/util/EventUtil.java
> +            ChangeInventoryEvent.Transfer.Post event =
Likewise here.

2017-07-25 16:27 UTC, gabizou commented on src/main/java/org/spongepowered/common/item/inventory/util/InventoryUtil.java
> +        for (EnumFacing enumfacing : EnumFacing.Plane.HORIZONTAL) {
Javadoc it as such.

2017-07-25 16:27 UTC, gabizou commented on src/main/java/org/spongepowered/common/mixin/core/tileentity/MixinTileEntityHopper.java
> +        itemStack1 = EventUtil.handleTransferPost(((TileEntityHopper)(Object) this), i, itemStack, iInventory, itemStack1);
Does the variable assignment really matter?\

2017-07-25 17:04 UTC, Zidane commented on src/main/java/org/spongepowered/common/item/inventory/util/EventUtil.java
> +public final class EventUtil {
@gabizou is right on point. Too many utils make for very messy code and should be consolidated down.

2017-10-23 03:33 UTC, gabizou commented on testplugins/src/main/java/org/spongepowered/test/TransferEventTest.java
> +    public void onPreTransferEvent(ChangeInventoryEvent.Transfer.Pre event) {
This listener needs to be toggle able, instead of requiring everyone to disable the plugin annotation ;)

2017-10-23 17:06 UTC, Deamon5550 requested changes

2017-10-23 17:06 UTC, Deamon5550 commented on src/main/java/org/spongepowered/common/event/SpongeCommonEventFactory.java
> +            Sponge.getCauseStackManager().pushCause(te);
Never popped?

2017-11-01 16:33 UTC, merged