Add Projectile Test Plugin
SpongePowered/Sponge pull request #1424
Opened 2017-07-08 12:14 UTC by ryantheleach

I made a test plugin whilst testing what Projectile events and causes were currently being thrown, Figured I'd chuck it your way if you were interested.

2017-07-09 05:21 UTC, gabizou requested changes
Just style changes then ready for merging 👍 Good addition for the test plugin suite.

2017-07-09 05:21 UTC, gabizou commented on testplugins/src/main/java/org/spongepowered/test/ProjectileTest.java
> +    @Listener public void onGameStartingServer(GameStartingServerEvent event) {
Annotations on a new line.

2017-07-09 05:21 UTC, gabizou commented on testplugins/src/main/java/org/spongepowered/test/ProjectileTest.java
> +                , "logProjectiles");
If you're going to have things on separate lines, the comma is needed on the previous line and the parentheses on a new line.

2017-07-09 05:21 UTC, gabizou commented on testplugins/src/main/java/org/spongepowered/test/ProjectileTest.java
> +        title("LaunchProjectile");
Are you using `this` to qualify methods or not? Keep it uniform please ;)

2017-07-09 09:11 UTC, ryantheleach commented
I realized afterwards it would simplify the listening code if I just made the command register the listeners, I had to put it into an inner class, otherwise the listeners would have been enabled by default and needed to be removed.

2017-11-23 00:18 UTC, parlough approved these changes
Seems like a useful test to add to me.

2018-01-01 09:40 UTC, Meronat commented
@ryantheleach You have this in your to-do list, is there anything else you'd like to do with this or is it good to be merged in?

2018-01-03 02:18 UTC, ryantheleach commented
@Meronat I've just come back from holiday, and will start working on my TODO lists, on days that my bedroom is cooler then the surface of the sun.

2019-07-06 14:50 UTC, merged