Implemented the Record API.
SpongePowered/Sponge pull request #1438
Opened 2017-07-14 20:16 UTC by Cybermaxke

[API](https://github.com/SpongePowered/SpongeAPI/pull/1609) | **Common**

Implements the features added by the API. Also implements the `getDefaultProperty` method in the `ItemStack`.

2017-07-14 22:22 UTC, kashike requested changes

2017-07-14 22:22 UTC, kashike commented on src/main/java/org/spongepowered/common/mixin/core/entity/player/MixinEntityPlayerMP.java
> +        this.connection.sendPacket(new SPacketEffect(1010, pos,
Extract `1010` to a constant somewhere, and use it here and any other occurrences.

2017-07-14 22:22 UTC, kashike commented on src/main/java/org/spongepowered/common/mixin/core/entity/player/MixinEntityPlayerMP.java
> +        final BlockPos pos = new BlockPos(position.getX(), position.getY(), position.getZ());
There's a method in `VecHelper` to convert.

2017-07-14 22:22 UTC, kashike commented on src/main/java/org/spongepowered/common/mixin/core/world/MixinWorldServer.java
> +                1010, pos, recordType == null ? 0 : ((SpongeRecordType) recordType).getInternalId(), false), getDimensionId());
See note about `1010` above.

2017-08-10 22:10 UTC, Meronat commented
Rebasing this on bleeding and running this caused no errors/test issues and the test plugin worked as intended for me. 

The test plugin uses the deprecated `getItem()` instead of `getType()` though.

2017-08-10 22:39 UTC, parlough approved these changes
Good addition, worked well for me after rebasing on bleeding.

2017-08-10 22:39 UTC, Meronat commented on testplugins/src/main/java/org/spongepowered/test/RecordTest.java
> +    public void onInit(GameInitializationEvent event) {
Can remove this listener, you don't use it.

2017-08-10 22:39 UTC, Meronat commented on testplugins/src/main/java/org/spongepowered/test/RecordTest.java
> +            } else if (itemStack.getItem() == ItemTypes.SPONGE) {
Switch to `itemStack.getType()`

2017-08-11 15:40 UTC, closed without merging