Implement rewrite of inventory queries.
SpongePowered/Sponge pull request #1440
Opened 2017-07-15 01:55 UTC by JBYoshi

[SpongeAPI](https://github.com/SpongePowered/SpongeAPI/pull/1610) | **SpongeCommon**

When inventories were first added, they had support for querying for sub-inventories based on various attributes about them. One of those attributes was the type of `ItemStack` they contained. However, sometimes, developers want to use the quantity of the `ItemStack`, and sometimes they want to ignore it but keep the data on it. Originally, the way to specify this was through a quantity of `-1`. Then Minecraft dropped support for negative quantities. Sponge left in its wake a `queryAny()` method that ignored the quantity. In a discussion earlier today, Mumfrey decided this system needed to change, and I decided to be the one to write it. This version exposes a `QueryOperation` that tells the query how to treat each argument. It should also be more flexible than the current system in case Minecraft breaks some other behavior in the future.

Closes https://github.com/SpongePowered/SpongeCommon/issues/1431.

2017-07-15 06:17 UTC, kashike requested changes

2017-07-15 06:17 UTC, kashike commented on src/main/java/org/spongepowered/common/item/inventory/query/SpongeQueryOperationType.java
> +        return newInstance.apply(arg);
`this.`

2017-07-15 06:17 UTC, kashike commented on src/main/java/org/spongepowered/common/registry/CommonModuleRegistry.java
> -import org.spongepowered.api.data.type.*;
undo

2017-07-15 12:55 UTC, JBYoshi commented on src/main/java/org/spongepowered/common/registry/CommonModuleRegistry.java
> -import org.spongepowered.api.data.type.*;
I went back through all the imports only to find that IntelliJ undid all of my changes... then I pressed the "undo" button and it immediately went back through and "fixed" the imports for me... :rage:

2017-07-15 13:00 UTC, JBYoshi commented on src/main/java/org/spongepowered/common/item/inventory/query/SpongeQueryOperationType.java
> +        return newInstance.apply(arg);
Fixed.

2017-08-11 16:23 UTC, Zidane commented
@JBYoshi Is this ready to go?

@Faithcaio @Mumfrey How is this looking?

2018-01-01 06:23 UTC, merged