Implement Inventory set operations
SpongePowered/Sponge pull request #1451
Opened 2017-07-19 18:45 UTC by Faithcaio

[SpongeAPI](https://github.com/SpongePowered/SpongeAPI/pull/1616) | *SpongeCommon*

2017-07-19 18:48 UTC, Faithcaio commented
@Mumfrey is gridInventory.query(InventoryRow.class) supposed to just return itself?
How would you get the Rows then?

2017-07-21 14:18 UTC, Mumfrey reviewed
Minor things

2017-07-21 14:18 UTC, Mumfrey commented on src/main/java/org/spongepowered/common/item/inventory/lens/CompoundSlotProvider.java
> +    private List<SlotLens<TInventory, TStack>> slotList = new ArrayList<>();
`final`?

2017-07-21 14:18 UTC, Mumfrey commented on src/main/java/org/spongepowered/common/item/inventory/lens/impl/CompoundLens.java
> +    protected List<Lens<IInventory, ItemStack>> inventories;
also `final`?

2017-07-21 14:18 UTC, Mumfrey commented on src/main/java/org/spongepowered/common/item/inventory/query/Query.java
> +        List<Fabric<TInventory>> fabricList = new ArrayList<>();
Potentially use builder pattern for `CompoundFabric` & `CompoundLens` rather than list passed to ctor lower down?

2017-07-22 13:31 UTC, kashike requested changes

2017-07-22 13:31 UTC, kashike commented on src/main/java/org/spongepowered/common/item/inventory/lens/CompoundSlotProvider.java
> +            if (!slotList.contains(slotLens)) {
`this.` (and next line)

2017-07-22 13:31 UTC, kashike commented on src/main/java/org/spongepowered/common/item/inventory/EmptyInventoryImpl.java
> +        return this == inventory;
`return this instanceof EmptyInventoryImpl;`? Or is it intentional to only have the same inventory return `true`?

2017-07-22 14:15 UTC, Faithcaio commented on src/main/java/org/spongepowered/common/item/inventory/EmptyInventoryImpl.java
> +        return this == inventory;
Well i'm not sure.
If this were strictly a set operation it should still return true for other empty inventories.
But as containsInventory checks for the actual structure being inside the other inventory I think this is correct.

@Mumfrey ?

2017-07-25 15:57 UTC, closed without merging

2017-07-25 16:02 UTC, kashike commented
https://github.com/SpongePowered/SpongeCommon/commit/f28f45adbdc7e1f308d3b293f3a49b8d09d019dc