Allow sending a specific page of a pagination list and add a test plugin
SpongePowered/Sponge pull request #1475
Opened 2017-08-05 03:14 UTC by Meronat

[SpongeAPI]() | SpongeCommon

Accomplishes part of https://github.com/SpongePowered/SpongeCommon/pull/1305

Cleans up some small messages as well.

2017-08-05 12:33 UTC, JBYoshi approved these changes

2017-08-06 08:10 UTC, ST-DDT requested changes

2017-08-06 08:10 UTC, ST-DDT commented on src/main/java/org/spongepowered/common/service/pagination/SpongePaginationList.java
> +        checkNotNull(this.contents, "The contents of the pagination list cannot be null!");
This is a final field. This should be validated in the constructor.

2017-08-07 02:05 UTC, Meronat commented on src/main/java/org/spongepowered/common/service/pagination/SpongePaginationList.java
> +        checkNotNull(this.contents, "The contents of the pagination list cannot be null!");
It's validated in the builder build method, so I just removed this check.

2017-08-07 07:11 UTC, ST-DDT commented on src/main/java/org/spongepowered/common/service/pagination/SpongePaginationBuilder.java
> +        }
IMO its more likely to be an error to not specify the contents. So this should throw an ISException. But it does not really matter.

2017-08-07 07:30 UTC, ST-DDT approved these changes

2017-08-09 22:33 UTC, Meronat commented on src/main/java/org/spongepowered/common/service/pagination/SpongePaginationBuilder.java
> +        }
I have made this change

2017-08-10 02:45 UTC, kashike requested changes

2017-08-10 02:45 UTC, kashike commented on src/main/java/org/spongepowered/common/service/pagination/IterablePagination.java
> +            throw new CommandException(t("You cannot go backwards in an IterablePagination."));
Perhaps phrase this exception message a different way? This sounds weird.

2017-08-10 02:45 UTC, kashike commented on src/main/java/org/spongepowered/common/service/pagination/ListPagination.java
> +            throw new CommandException(t("Page %s is too high!", page));
Include the maximum page?
`"Page %s is greater than %s."`?

2017-08-10 02:45 UTC, kashike commented on src/main/java/org/spongepowered/common/service/pagination/SpongePaginationBuilder.java
> +        checkNotNull(padding, "The padding cannot be null!");
unnecessary

2017-08-10 02:45 UTC, kashike commented on src/main/java/org/spongepowered/common/service/pagination/SpongePaginationBuilder.java
> +            throw new IllegalStateException("The contents of the pagination list cannot be null!");
use `checkState`

2017-08-10 02:59 UTC, Meronat commented on src/main/java/org/spongepowered/common/service/pagination/IterablePagination.java
> +            throw new CommandException(t("You cannot go backwards in an IterablePagination."));
`You cannot go to previous pages in an IterablePagination.`?

2017-08-10 03:05 UTC, kashike commented on src/main/java/org/spongepowered/common/service/pagination/IterablePagination.java
> +            throw new CommandException(t("You cannot go backwards in an IterablePagination."));
Sure.

2017-08-10 21:15 UTC, closed without merging