Implements the API for scoreboard tags
SpongePowered/Sponge pull request #1490
Opened 2017-08-16 23:34 UTC by Meronat

[SpongeAPI](https://github.com/SpongePowered/SpongeAPI/pull/1633) | SpongeCommon

Implements the data API interfaces for the TagsData often used by scoreboard related commands.

Supersedes https://github.com/SpongePowered/SpongeCommon/pull/960

2017-08-16 23:39 UTC, Meronat commented on src/main/java/org/spongepowered/common/data/processor/data/entity/TagsDataProcessor.java
> +        // Minecraft does not allow there to be more than 1024 tags.
Another option is to add all of them one by one, keeping track of which ones were added successfully, then removing them all again if one of them failed to be added.

2017-08-16 23:41 UTC, Meronat commented on src/main/java/org/spongepowered/common/data/processor/data/entity/TagsDataProcessor.java
> +        // Minecraft does not allow there to be more than 1024 tags.
I'm actually going to switch to that option in-case some entity in a mod overrides the `addTag()` method.

2017-08-17 09:00 UTC, kashike requested changes

2017-08-17 09:00 UTC, kashike commented on src/main/java/org/spongepowered/common/data/manipulator/mutable/entity/SpongeTagsData.java
> +        this(new HashSet<>());
`Collections.emptySet()`

2018-05-08 08:59 UTC, Meronat commented
Will update this soon so we can get it into API 7.1

2018-06-15 21:53 UTC, merged