Implement SizeData
SpongePowered/Sponge pull request #1492
Opened 2017-08-18 01:01 UTC by Meronat

[SpongeAPI](https://github.com/SpongePowered/SpongeAPI/pull/1636) | **SpongeCommon**

Supersedes https://github.com/SpongePowered/SpongeCommon/pull/402

Implements size data based on Hassan's changes, but with some changes to the API and implementation, including the inclusion of a modified version of his test plugin. 

With this PR you can modify the base_size(width) and height, but developers have to keep in mind that this only changes the bounding box, it isn't super reliable, and Sponge(maybe Minecraft idk) limits the max size of a bounding box to 1000.

I am open to changes everywhere, from documentation to functionality, so please give this a good review.

2017-09-07 18:20 UTC, Meronat commented
I can go ahead and fix these merge conflicts sometime today or tomorrow. If anyone would like to see any other changes please bring them up.

2017-09-09 00:06 UTC, kashike requested changes

2017-09-09 00:06 UTC, kashike commented on src/main/java/org/spongepowered/common/data/manipulator/immutable/entity/ImmutableSpongeSizeData.java
> +        checkArgument(scale > 0, "The base size must be greater than 0.");
Should be `base > 0`.

2019-12-02 19:34 UTC, closed without merging

2019-12-02 19:37 UTC, gabizou commented
This will need to be re-done and re-target `api-8`. Bleeding is no longer a valid branch.