Update implementation for ContextValue
SpongePowered/Sponge pull request #1528
Opened 2017-09-15 18:45 UTC by gabizou

[SpongeAPI](https://github.com/SpongePowered/SpongeAPI/pull/1648) | **SpongeCommon**

This updates the implementation, borrowing the implementation of previously `NamedCauseFilter`.

2017-09-15 19:17 UTC, kashike requested changes

2017-09-15 19:17 UTC, kashike commented on src/test/java/org/spongepowered/common/event/listener/ContextValueCauseListener.java
> +package org.spongepowered.common.event.listener;
license header

2017-09-15 22:17 UTC, Deamon5550 requested changes

2017-09-15 22:17 UTC, Deamon5550 commented on src/main/java/org/spongepowered/common/event/filter/delegate/NamedCauseFilterSourceDelegate.java
> +        this.anno = anno;
Assert here that the id in the annotation is a valid key and throw an exception if not.

2017-09-15 22:17 UTC, Deamon5550 commented on src/main/java/org/spongepowered/common/event/filter/delegate/NamedCauseFilterSourceDelegate.java
> +        mv.visitMethodInsn(INVOKEVIRTUAL, Type.getInternalName(Cause.class), "getContext", "()" + Type.getDescriptor(EventContext.class), false);
Throw an exception here if the parameter type does not match the type of the key.

2017-09-15 22:17 UTC, Deamon5550 commented on src/main/java/org/spongepowered/common/event/filter/delegate/NamedCauseFilterSourceDelegate.java
> +        this.anno = anno;
This filter delegate should be creating a field in the filter holding the `EventContextKey` which is fetched from the registry by id when the filter is initialized (look at the subtype filter for how creating a field and putting stuff into the initializer works)

2017-09-15 22:17 UTC, Deamon5550 commented on src/test/java/org/spongepowered/common/event/listener/ContextValueCauseListener.java
> +        this.namedCauseListenerCalledEx = true;
this needs to be inverted since you are testing for false

2018-02-01 00:34 UTC, ryantheleach commented
Closed by @Zidane , See API PR.

2018-02-01 04:29 UTC, Deamon5550 commented
@ryantheleach this PR is still needed as the `ContextValue` filter is still not implemented. The api pr had adjacent changes which is what @Zidane was rejecting.

2019-06-20 07:25 UTC, closed without merging