Implement AITargetEvent
SpongePowered/Sponge pull request #1582
Opened 2017-11-01 16:45 UTC by Faithcaio

[SpongeAPI](https://github.com/SpongePowered/SpongeAPI/pull/1679) | [SpongeCommon]()

2017-11-02 12:38 UTC, JBYoshi requested changes

2017-11-02 12:38 UTC, JBYoshi commented on src/main/java/org/spongepowered/common/event/SpongeCommonEventFactory.java
> +        return SpongeEventFactory.createAITargetEvent(Sponge.getCauseStackManager().getCurrentCause(), target, agent);
You still need to post the event. I think it’s a method in `SpongeImpl`.

2017-11-12 09:05 UTC, parlough approved these changes

2017-11-12 09:20 UTC, kashike approved these changes

2017-11-12 09:21 UTC, merged