Add test plugin WitherSpawnTest
SpongePowered/Sponge pull request #1599
Opened 2017-11-16 16:30 UTC by ryantheleach

Spams chat with spawn causes, to enable, change chatSpawns to true.

It's a bit crap at the moment, Feel free to suggest changes.

2017-11-16 17:15 UTC, phit commented
add a command to toggle it on and off?

2017-11-17 01:03 UTC, gabizou requested changes

2017-11-17 01:03 UTC, gabizou commented on testplugins/src/main/java/org/spongepowered/test/WitherSpawnTest.java
> +    final boolean chatSpawns = false;
Command based toggle maybe?

2017-11-17 01:03 UTC, gabizou commented on testplugins/src/main/java/org/spongepowered/test/WitherSpawnTest.java
> +        if(!chatSpawns) return;
Formatting.... spacing....

2017-11-17 01:03 UTC, gabizou commented on testplugins/src/main/java/org/spongepowered/test/WitherSpawnTest.java
> +                Text.of(TextColors.GREEN, "Spawning: ", entities, " ", TextColors.WHITE, event.getCause().toString())
You shouldn't have to call `event.getCause().toString()`, `event.getCause()` should suffice, no?

2017-11-17 01:03 UTC, gabizou commented on testplugins/src/main/java/org/spongepowered/test/WitherSpawnTest.java
> +        if(!chatSpawns) return;
Formatting here as well.

2017-11-17 02:51 UTC, ryantheleach commented
@gabizou as for the functionality, is it ok as is? Or is there any large features you would think would help?

2019-02-01 21:39 UTC, ImMorpheus commented
Updated and rebased

2019-02-01 22:02 UTC, merged