[WIP] Refactor and implement ChangeDataHolderEvent.ValueChange
SpongePowered/Sponge pull request #1605
Opened 2017-11-19 03:53 UTC by Aaron1011

[SpongeAPI](https://github.com/SpongePowered/SpongeAPI/pull/1695) | SpongeCommon | [SpongeForge](https://github.com/SpongePowered/SpongeForge/pull/1866)

See the SpongeAPI PR for more details.

This is the basic pattern for firing a `ChangeDataHolderEvent.ValueChange` event for a given key:

1. Redirect all locations in Vanilla/Forge where the value is set. Ideally, there will be a public setter method for you to inject into.
2. Instead of setting the underlying field (or `DataParameter, etc`), call `offerWithEvent` on the appropriate `DataHolder`, putting any relevant objects into the `Cause`
3. In the `ValueProcessor` for the key in question, **bypass** the setter you redirected before, if applicable. This ensures that setting the value does not end up recursing infinitely between your redirected setter and the value processor.

Basically, the idea is to ensure that all changes done by mods/vanilla/forge end up firing an event, while API changes (e.g. anything going through the value processor) does **not**. The decision as to whether or not to fire an event for a plugin change is handled on the API side, and is not the implementation's concern.

2017-12-03 21:45 UTC, gabizou requested changes
Small changes, otherwise looks good. Aside from API discussions we've had about removing GetKey annotation.

2017-12-03 21:45 UTC, gabizou commented on src/main/java/org/spongepowered/common/data/AbstractArchetype.java
> +        throw new UnsupportedOperationException();
Message maybe?

2017-12-03 21:45 UTC, gabizou commented on src/main/java/org/spongepowered/common/data/AbstractArchetype.java
> +                .flatMap(processor -> processor.readFrom(this.data).map(v -> v.getDefault()));
multi-line the nested mapping. In the event there's an exception, we want to be able to pinpoint which lambda is having an issue.

2017-12-03 21:45 UTC, gabizou commented on src/main/java/org/spongepowered/common/data/DataProcessor.java
> +    //void setWithEvent(DataHolder container, M manipulator, Cause cause);
Intended to be used later maybe? comments welcome.

2017-12-03 21:45 UTC, gabizou commented on src/main/java/org/spongepowered/common/data/processor/common/AbstractBlockOnlyDataProcessor.java
> +import org.spongepowered.api.event.data.ChangeDataHolderEvent;
imports?

2017-12-03 21:45 UTC, gabizou commented on src/main/java/org/spongepowered/common/mixin/core/util/MixinFoodStats.java
> +    @Inject(method = "addStats(Lnet/minecraft/item/ItemFood;Lnet/minecraft/item/ItemStack;)V", at = @At(value = "HEAD"))
This should be a redirect if you're modifying the cause stack, this way you can wrap it in a try with autocloseable frames.

2017-12-03 21:45 UTC, gabizou commented on testplugins/src/main/java/org/spongepowered/test/FoodChangeTest.java
> +public class FoodChangeTest {
If this is going to constantly print to the player, should make it a toggle to join in (reduces the amount of commenting when debugging implementation).

2017-12-03 21:45 UTC, gabizou commented on testplugins/src/main/java/org/spongepowered/test/InjectionTest.java
> +import org.spongepowered.api.data.key.Keys;
imports.

2018-01-20 23:12 UTC, Meronat commented
Going to close this for now due to https://github.com/SpongePowered/SpongeAPI/pull/1728 and https://github.com/SpongePowered/SpongeCommon/pull/1670 which provide a method of implementing and listening to the event.

2018-01-20 23:12 UTC, closed without merging