[WIP] Implement CreatePortalEvent.
SpongePowered/Sponge pull request #1608
Opened 2017-11-22 19:03 UTC by JBYoshi

Supports:
[x] Lighting nether portals
[x] Nether portals created after teleportation
[ ] Inserting ender eyes into End portals
[ ] Spawning the End exit portal

Fixes #1559.

2017-11-22 19:10 UTC, kashike requested changes

2017-11-22 19:10 UTC, kashike commented on testplugins/src/main/java/org/spongepowered/test/PortalTest.java
> +package org.spongepowered.test;
license

2017-11-22 19:11 UTC, JBYoshi commented on testplugins/src/main/java/org/spongepowered/test/PortalTest.java
> +package org.spongepowered.test;
Fixed.

2017-11-23 01:40 UTC, ryantheleach commented
Consider adding support not only for the end portal, but end gateways.

2018-01-31 23:34 UTC, Zidane commented
@JBYoshi 

Status update?

2018-02-04 00:03 UTC, JBYoshi commented
@Zidane I found out that implementing this is going to be somewhat more difficult than I thought. My current approach for detecting portal constructions during teleports (by assuming all block placements during a teleport are part of a new portal) is unreliable. On the one hand, it doesn't work for detecting portals created for the first time. On the other hand, it improperly detects the [obsidian platform](https://minecraft.gamepedia.com/Generated_structures#Obsidian_platform) created when entering the End as a portal. I'll probably try to detect whether a block is a portal, but I don't know of a simple way to do that.

2018-02-04 17:40 UTC, ryantheleach commented
@JBYoshi I'd consider that platform as part of the portal personally, it's just the receiving end, Just like nether portals have a base when they are forced into air, the one way only exit of the end portal has a set platform in the end at a specific place in the end. As long as it's documented it's fine IMO, unless you can think of some good reasons why we would want to not include blocks created when a portal spawns in the events?

The main usecase I see, is people wanting to prevent all of the blocks being placed / created, so this is fine, maybe some docs or renaming of the method is required to make it more clear.

2018-02-22 22:41 UTC, gabizou commented on testplugins/src/main/java/org/spongepowered/test/PortalTest.java
> +        if (RANDOM.nextInt(5) == 0) {
Make this a toggle as well, I don't want to randomly be testing portals and wondering what this new mechanic where they suddenly explode :P

2018-02-22 22:41 UTC, gabizou commented on src/main/java/org/spongepowered/common/mixin/core/item/MixinItemEnderEye.java
> +        ConstructPortalEvent event = SpongeEventFactory.createConstructPortalEvent(Sponge.getCauseStackManager().getCurrentCause(),
Would we be able to add the blocks being changed for the portal?

2019-11-22 23:20 UTC, gabizou commented on src/main/java/org/spongepowered/common/entity/EntityUtil.java
> +                    ConstructPortalEvent constructPortalEvent = SpongeEventFactory.createConstructPortalEvent(Sponge.getCauseStackManager()
Can shortcut with `frame.getCurrentcause()` since we are already in a frame.

2020-06-28 15:14 UTC, Zidane commented
@JBYoshi Either update this or close it.

2020-06-29 03:36 UTC, JBYoshi commented
I'm going to go ahead and close this. This code seems to have broken since I last looked at it, and reimplementing it seems to be much more trouble than it's worth. I'm thinking of just getting rid of `ConstructPortalEvent` entirely. `ChangeBlockEvent` should suffice for most cases, and it provides much more information than `ConstructPortalEvent` could.

2020-06-29 03:36 UTC, closed without merging