Add a check if the user is running Java 9
SpongePowered/Sponge pull request #1639
Opened 2017-12-07 12:47 UTC by DoNotSpamPls

I'd like to note that this has not been tested (I will test when I have some free time).
If someone can check for errors or things that don't work, I will be very grateful 😃

2017-12-07 12:54 UTC, me4502 commented
I don’t see what you’ve done here. It seems you’ve just duplicated the previous message, and added another method to check for it (That isn’t even called anywhere)?

Java 9 isn’t supported in Sponge as a vast majority of the Minecraft Toolchain doesn’t support it at this current point in time. Work is being done, with it depending on the replacement for LaunchWrapper in the time being.

2017-12-07 13:07 UTC, ST-DDT requested changes
Please follow the formatting guidelines and check that it at least compiles.

2017-12-07 17:58 UTC, Deamon5550 requested changes
Also don't forget to actually call it.

2017-12-07 17:58 UTC, Deamon5550 commented on src/java6/java/org/spongepowered/launch/JavaVersionCheckUtils.java
> +                                              + "In order to run Sponge, you **must** be running JRE version %s (or above).\n"
This message does not make sense to a user running java 9.

2017-12-07 17:58 UTC, Deamon5550 commented on src/java6/java/org/spongepowered/launch/JavaVersionCheckUtils.java
> +            throw new RuntimeException(error);
You've removed the if but left the print after the throw, so this doesn't compile.

2017-12-07 17:58 UTC, Deamon5550 commented on src/java6/java/org/spongepowered/launch/JavaVersionCheckUtils.java
> +        if (getVersionValue(version) > getVersionValue(REQUIRED_VERSION)) {
This will cause all java 8 builds except build 20 to fail...

2017-12-13 05:30 UTC, gabizou commented
Code doesn't compile, doesn't accomplish a Java 9 check, and far more to the game would fail to load, even with a sponge check.

2017-12-13 05:30 UTC, closed without merging