Fix event generics.
SpongePowered/Sponge pull request #1681
Opened 2018-01-02 19:58 UTC by Cybermaxke

**Common** | Forge

2018-01-02 20:13 UTC, randombyte-developer commented
:+1: I didn't bother debugging the non-working listener and kept the 'old' PreInit event for the registration of Keys. Thanks for fixing it!

2018-01-03 03:16 UTC, gabizou requested changes

2018-01-03 03:16 UTC, gabizou commented on testplugins/src/main/java/org/spongepowered/test/myhomes/MyHomes.java
> +        event.register(DEFAULT_HOME);
Unless you changed the `SpongeKeyBuilder` implementation, this is redundant and should throw an exception for attempting double registration.

2018-01-03 03:16 UTC, gabizou commented on src/main/java/org/spongepowered/common/SpongeImpl.java
> -        ((SpongeEventManager) game.getEventManager()).post(event, true);
The reason why this was added is because on clients, this will not work unless allowing a client thread event is true.

2018-01-04 18:14 UTC, gabizou commented
I'm curious why you are requiring `Key`s to be registered through the event instead of through the `build()` method as it was originally designed (much like `DataRegistration` for that matter).

2018-01-04 18:49 UTC, Cybermaxke commented
@gabizou I think we should be consistent how we register stuff. And if we aren't going to use the `register` method then there is no point to register things inside event, might as well do it in the init event. `DataRegistration` would require it's `buildAndRegister` to be changed into `build` to fit into this concept.

2018-01-06 08:09 UTC, merged

2018-01-06 21:44 UTC, Cybermaxke commented
@gabizou This PR should also be merged into bleeding.

2018-01-07 17:59 UTC, dualspiral commented
@Cybermaxke I've pulled all the latest `stable-7` changes into `bleeding` now.