Fix #1282
SpongePowered/Sponge pull request #1710
Opened 2018-01-14 10:59 UTC by ImMorpheus

[SpongeAPI](https://github.com/SpongePowered/SpongeAPI/pull/1740) | SpongeCommon

Fix https://github.com/SpongePowered/SpongeCommon/issues/1282

2018-01-14 11:32 UTC, dualspiral requested changes

2018-01-14 11:32 UTC, dualspiral commented on src/main/java/org/spongepowered/common/mixin/core/entity/player/MixinEntityPlayerMP.java
> +        return new SpongeValue<>(Keys.LAST_DATE_PLAYED, Instant.EPOCH, SpongePlayerDataHandler.getLastPlayed(this.getUniqueID()).get());
I don't think this is the way to fix it. `lastPlayed` should indicate when the player indeed last played, which in the case of an online player is _right now_. This also breaks the expectation of other plugins that might use this, so even though this isn't an API change, it's a behavioral change and we should not be doing that either with good reason.

For a simple patch, setting some flag on the player (or other) object that states a player is on its first connection would be better, which would then get passed up through the API.

From what @ryantheleach said on the linked issue (to which I agree)

> LastJoined should be when a player last connected (successfully)
> LastPlayed should be the current instant, if the player is currently online.

Thus, the better solution here would to be to add a `Keys.LAST_DATE_JOINED` key which gets populated with the last join date. That should then be used for comparisons.

2018-01-14 12:52 UTC, ryantheleach commented
I think we need to split this into 2 PR's API 7.1 which just fixes hasPlayedBefore, and API 8 which fixes all the semantic errors in the naming.

To list a few:

It's important that hasPlayedBefore works differently then comparing those Instants and works correctly, as it should only be done when the players data is going/has been created? Otherwise it's going to cause issue's with importing worlds / players / migrating from other places, incorrectly assigning kits.

LastPlayed and FirstJoined are less important to get right IMO as they are meta-data, so working for a best-case is ok.

SpongePlayerDataHandler has a getFirstJoined(UUID) and a getLastPlayed(UUID)

Yet the API uses those to expose FirstPlayed , LastPlayed and hasPlayedBefore.

LastJoined is useful to have as well, but I'm wondering if there is any benefit or not of adding a FirstJoined to represent their first join attempt or not.

I could also see it being useful to plugins that wish to reset the hasPlayedBefore state, in regards to resetting a 'new player experience' if they have played for less then x minutes, and have been away for longer then y days.


So Number 1 priority, is fixing hasPlayedBefore, and maybe exposing it as data itself, This should be done on API 7.1 (as it's a fix and not a behavior change)

Priority 2, should be adding LastJoined which could also be added on API 7.1 and adding a deprecation warning to LastPlayed warning that the behavior will change in API 8, and that current users should move to LastJoined

API: 8

Priority 3, would be to modify LastPlayed to return the current time if the player is online, or the lastPlayed if they are offline. and would need to be done on API8 as it's a behavior break.

Priority 4, would be to make all these datapoints optional except hasPlayedBefore.

Because in all cases they might not have ever joined, might not have ever played, and that they might be offline at the time the methods are called on EntityPlayerMP, or hell might be FakePlayers that have never 'played'


I believe this is a correct summary of the points covered by @dualspiral @ImMorpheus and myself on the #voice channel on Discord.

2018-06-12 23:56 UTC, gabizou commented
Superseded by https://github.com/SpongePowered/SpongeCommon/commit/802ea1d1d7a81f8cc37322f313f19935ab24ba73

Going to break the API to correctly fix this later.

2018-06-12 23:56 UTC, closed without merging