Item TileEntity data
SpongePowered/Sponge pull request #1801
Opened 2018-02-13 18:33 UTC by Faithcaio

SpongeAPI | SpongeCommon TODO

solved https://github.com/SpongePowered/SpongeAPI/issues/1781

2020-06-10 05:12 UTC, gabizou requested changes
Gonna need to spend some time to debate this. While some *vanilla* `TileEntity` instances are directly inventory viewers, I don't want to blanket the idea of making these fake entities for all possible `TileEntity` instances. I'd much rather a whitelist approach, allowing the community to test the feature with modded `TE`'s, along with some GUI mods that might throw some nice exceptions on either the client or server for requesting a `TE` that doesn't exist.

That being said, there's some code here that can be used, but for the basis of representing an inventory, I'd lean on the "whitelist `TE` creation with a fallback to manual slotted inventory creation".

2020-06-10 05:12 UTC, gabizou commented on src/main/java/org/spongepowered/common/data/util/NbtDataUtil.java
> +            nbttagcompound.setInteger("x", -1);
Instead of using the string constants, use the field constants already set up for you to avoid future portability issues.

2020-06-28 15:16 UTC, Zidane commented
@Faithcaio Update this or close it for api-7.

2020-07-26 15:09 UTC, Zidane commented
@Faithcaio Is this still good? Needs to be redone for API-8.

2020-11-10 03:57 UTC, Zidane commented
Closing this unless a member from the community picks it back up.

2020-11-10 03:57 UTC, closed without merging