Implement API for Shulkers, ShulkerBullets and ShulkerBoxes
SpongePowered/Sponge pull request #2087
Opened 2018-08-31 14:27 UTC by RedNesto

[SpongeAPI](SpongePowered/SpongeAPI#1903) | **SpongeCommon**

This PR implements everything added to its SpongeAPI counterpart.

I hope I did all the DataAPI stuff right.

Reviews are welcome.

_Only tested with SpongeVanilla for now._

[Test Plugin](https://gist.github.com/RedNesto/6fdd0d1e8ce66a52374432e1544c43ba)

2018-08-31 14:42 UTC, XakepSDK commented on src/main/java/org/spongepowered/common/data/processor/data/entity/EntityTargetedEntityDataProcessor.java
> +        if (!(dataHolder instanceof IEntityTargetingEntity))
Braces

2018-08-31 14:42 UTC, XakepSDK commented on src/main/java/org/spongepowered/common/data/processor/data/entity/EntityTargetedEntityDataProcessor.java
> +        if (!(dataHolder instanceof IEntityTargetingEntity))
Braces

2018-08-31 14:43 UTC, XakepSDK commented on src/main/java/org/spongepowered/common/data/processor/data/entity/ShulkerDyeColorDataProcessor.java
> +        if (!(container instanceof IMixinShulker))
Braces

2018-08-31 14:43 UTC, XakepSDK commented on src/main/java/org/spongepowered/common/data/processor/data/entity/ShulkerDyeColorDataProcessor.java
> +        if (!(container instanceof IMixinShulker))
Braces

2018-08-31 15:17 UTC, ImMorpheus submitted a review, later dismissed

2018-08-31 15:17 UTC, ImMorpheus commented on src/main/java/org/spongepowered/common/mixin/core/entity/MixinEntityShulkerBullet.java
> +        manipulators.add(new SpongeTargetedEntityData());
This is wrong. It's always returning an empty target.

2018-08-31 16:46 UTC, ImMorpheus requested changes

2018-08-31 16:46 UTC, ImMorpheus commented on src/main/java/org/spongepowered/common/mixin/core/entity/MixinEntityShulkerBullet.java
> +        if (projectileSource != null) {
this

2018-09-05 10:12 UTC, ImMorpheus requested changes
As in the signsource PR, add the test plugin source as a proper test plugin.

2019-03-16 16:32 UTC, ImMorpheus approved these changes

2019-03-16 16:44 UTC, merged