Force auto-populate into global config
SpongePowered/Sponge pull request #2092
Opened 2018-09-02 17:14 UTC by phit

Fixes #2076 

still gonna use the value of auto-populate per world, as you may want to disable things from one dimensions being added to the config for whatever reason

still need to figure out how to handle collision configs

2018-09-02 18:45 UTC, lucko requested changes
Looks ok, other than that the value reads should still be made from the active (world/dim specific) config instances, other than global.

2018-09-02 18:45 UTC, lucko commented on src/main/java/org/spongepowered/common/mixin/entitycollisions/MixinBlock_Collisions.java
>          this.setMaxCollisions(collisionCat.getMaxEntitiesWithinAABB());
The value should still be read from the `activeConfig` instance, to allow for per-world overrides.

2018-09-02 18:45 UTC, lucko commented on src/main/java/org/spongepowered/common/mixin/entitycollisions/MixinEntity_Collisions.java
>          this.maxCollisions = collisionCat.getMaxEntitiesWithinAABB();
The value should still be read from the `activeConfig` instance, to allow for per-world overrides.

2018-09-02 18:45 UTC, lucko commented on src/main/java/org/spongepowered/common/mixin/plugin/entityactivation/EntityActivationRange.java
>          Integer defaultActivationRange = activationCategory.getDefaultRanges().get(entityType);
The value should still be read from the `config` instance, to allow for per-world overrides.

2018-09-02 18:45 UTC, lucko commented on src/main/java/org/spongepowered/common/mixin/plugin/tileentityactivation/TileEntityActivation.java
>          int defaultRange = activationCategory.getDefaultBlockRange();
Same as other places, the value should be read from the "active" `config` instance.

2018-09-02 18:51 UTC, lucko commented on src/main/java/org/spongepowered/common/mixin/plugin/entityactivation/EntityActivationRange.java
>          Integer defaultActivationRange = activationCategory.getDefaultRanges().get(entityType);
Nevermind, doesn't apply here.

2018-09-02 18:51 UTC, lucko commented on src/main/java/org/spongepowered/common/mixin/plugin/tileentityactivation/TileEntityActivation.java
>          int defaultRange = activationCategory.getDefaultBlockRange();
Nevermind, doesn't apply here.

2018-09-21 14:27 UTC, Shybella commented
is this getting added?

2018-09-27 00:33 UTC, merged