Implement methods for RailDirection and LogAxis
SpongePowered/Sponge pull request #2474
Opened 2020-01-09 21:36 UTC by Lignium

[SpongeAPI](https://github.com/SpongePowered/SpongeAPI/pull/2078) | **SpongeCommon**

Implements the methods that introduced by https://github.com/SpongePowered/SpongeAPI/pull/2078.

2020-04-26 09:06 UTC, gabizou requested changes

2020-04-26 09:06 UTC, gabizou commented on src/main/java/org/spongepowered/common/mixin/api/mcp/block/BlockRailBase_EnumRailDirectionMixin_API.java
> +            case 2:
All of these magic numbers need to be Constants in the `org.spongepowered.common.util.Constants`, whether it's in a new nested class for Rail Directions or whatever.

2020-04-26 09:06 UTC, gabizou commented on src/main/java/org/spongepowered/common/mixin/api/mcp/block/BlockLog_EnumAxisMixin_API.java
> +        switch ((BlockLog.EnumAxis) (Object) this) {
Would it make better sense to just stick the `o.s.a.Axis` as a bridge method on `EnumAxis`? I don't like switch statements as is.

2020-04-26 16:37 UTC, Lignium commented on src/main/java/org/spongepowered/common/mixin/api/mcp/block/BlockLog_EnumAxisMixin_API.java
> +        switch ((BlockLog.EnumAxis) (Object) this) {
@gabizou Еxcuse me, I didn't catch your thought. What is the `o.s.a.`? How can I avoid using `switch` other than replacing them with `if`?

2020-05-31 14:26 UTC, dualspiral commented on src/main/java/org/spongepowered/common/mixin/api/mcp/block/BlockLog_EnumAxisMixin_API.java
> +        switch ((BlockLog.EnumAxis) (Object) this) {
`org.spongepowered.api`

2021-07-23 15:16 UTC, closed without merging