Don't handle health data changes on player spawn
SpongePowered/Sponge pull request #2484
Opened 2020-01-22 08:32 UTC by Lignium

Fixes a bug, the essence of which is that when a player logs in, `ChangeDataHolderEvent.ValueChange` is called, which indicates a change of health. However, these calls are made when the player’s entity is constructing and deserializing, and should not be construed as a real data change.

Resolves my issue on the forum: https://forums.spongepowered.org/t/strange-firing-of-changedataholderevent-valuechange-when-player-entry/34701

2020-01-26 15:44 UTC, gabizou requested changes
Functionality wise looks good. Please abide by the naming conventions outlined on the [wiki regarding bridges and injections](https://github.com/SpongePowered/SpongeCommon/wiki/Implementation-Policy:-Bridges-and-Mixins).

2020-01-26 15:44 UTC, gabizou commented on src/main/java/org/spongepowered/common/mixin/core/entity/EntityLivingBaseMixin.java
> +    private void onInitHealth(final EntityLivingBase entity, final float health) {
method name should be `impl$initializeHealthSilently`

2020-01-26 15:44 UTC, gabizou commented on src/main/java/org/spongepowered/common/mixin/core/entity/EntityLivingBaseMixin.java
> +        DataParameter<Float> healthParameter = EntityLivingBaseAccessor.accessor$getHealthParameter();
`final` value please.

2020-01-26 15:44 UTC, gabizou commented on src/main/java/org/spongepowered/common/mixin/core/entity/EntityLivingBaseMixin.java
> +        float clampedValue = MathHelper.clamp(health, 0.0F, this.getMaxHealth());
And this too.

2020-01-26 15:44 UTC, gabizou commented on src/main/java/org/spongepowered/common/mixin/core/network/datasync/EntityDataManagerMixin.java
> +        EntityDataManager.DataEntry<T> dataentry = this.getEntry(key);
`final`

2020-01-26 15:44 UTC, gabizou commented on src/main/java/org/spongepowered/common/bridge/network/datasync/EntityDataManagerBridge.java
> +    <T> void setSilently(DataParameter<T> key, T value);
Method name should be `bridge$setSilently`

2020-01-26 15:46 UTC, gabizou commented on src/main/java/org/spongepowered/common/mixin/core/entity/EntityLivingBaseMixin.java
> +    @Redirect(method = {"<init>", "readEntityFromNBT"}, at = @At(value = "INVOKE", target = "Lnet/minecraft/entity/EntityLivingBase;setHealth(F)V"))
Javadoc why this is being done, link to the issue if need be. on the surface it doesn't look like it's changing anything except using a more direct approach to setting health (which honestly, might affect some mods).

2020-01-26 15:49 UTC, gabizou commented
I realize your submission of the fix is related to a side-effect you're encountering and reported on the forums, but as we'd like to keep track of issues with commits and mixins, I'd like to ask if you could open an issue on SpongeCommon to simply keep discussion and reference back. I'm tentative on the merge of these changes as the potential hooks not being called for mods (by redirecting `setHealth`, you could be missing a bunch of mod injected hooks to that method).

I'm not quite sure your approach is needed here, as we might have an alternative option for resolving your issue.

2020-01-26 22:45 UTC, Lignium commented
@gabizou I will definitely create an issue a little later. I hope you will help me in resolving this issue. :)

2020-04-24 18:36 UTC, ImMorpheus commented
This and other similar cases should be covered by https://github.com/SpongePowered/SpongeCommon/pull/2580

2020-04-24 18:36 UTC, closed without merging