Add missing data to "supplyVanillaManipulators" methods for entities
SpongePowered/Sponge pull request #2493
Opened 2020-01-28 01:10 UTC by Lignium

This PR fully (with some exceptions) implements methods such as `Entity#getValues​()`, `Entity#getKeys()`, `Entity#getContainers()`.

Some keys were simply not implemented (PRs implementing them were canceled due to the closing of the bleeding branch), which means that they are in principle not available in official Sponge implementations:

- _SizeData_ (`Keys.BASE_SIZE`, `Keys.HEIGHT`, `Keys.SCALE`) — https://github.com/SpongePowered/SpongeCommon/pull/1492
- _SleepingData_ and _IgnoreSleepingData_ (`Keys.IS_SLEEPING`, `Keys.IGNORE_SLEEPING`) — https://github.com/SpongePowered/SpongeCommon/pull/1488

Just unimplemented data:

- _DamagingData_ (`Keys.ATTACK_DAMAGE`, `Keys.DAMAGE_ENTITY_MAP`)
- _ShatteringData_ (`Keys.WILL_SHATTER`)

And some just don't have a `DataManipulator`:

- _LlamaData_ (`Keys.LLAMA_STRENGTH`, `Keys.LLAMA_VARIANT`)

2020-01-31 19:32 UTC, ImMorpheus requested changes
Please don't add/remove newlines and move methods around. It adds noise to the diff, making it more difficult to review this PR.

2020-02-22 04:13 UTC, gabizou approved these changes
Looks good to me. I'll try to getting to test some of this out with all entity types being spawned and calling the methods to verify what datas are available on them and what aren't, I might include that test as a pseudo integration test or unit test, depending on which one I'm able to mock better.

2020-03-16 19:39 UTC, ImMorpheus approved these changes

2020-03-16 19:59 UTC, ImMorpheus commented
Working as intended. 
Tested with the following command executor:
```
for (EntityType type : Sponge.getRegistry().getAllOf(EntityType.class)) {
    try {
        ((Player) src).getWorld().createEntity(type, ((Player) src).getPosition()).getContainers();
    } catch (Exception e) {
        System.err.println("Error: " + e.getMessage());
    }
}
```
Output: (the following exceptions are not caused by these changes).
```
[Server thread/INFO]: Error: Cannot construct minecraft:complexpart please look to using entity types correctly!
[Server thread/INFO]: Error: There was an issue attempting to construct minecraft:fishinghook
[Server thread/INFO]: Error: Cannot construct minecraft:player please look to using entity types correctly!
```

2020-03-16 23:07 UTC, merged