Start moving some simpler things to new tracker package [API-8].
SpongePowered/Sponge pull request #2499
Opened 2020-02-07 04:13 UTC by i509VCB

Moves Bone meal handling and DragonFightManager tracker hooks to the tracker mixin package.

Also converted the large overwrite in the old DragonFightManagerMixin and replaced it with a redirect (gabizou you'll want to make sure I didn't royally screw up here lol) since the reference to process the dragonSpawnState only occurs once.

2020-02-07 04:29 UTC, gabizou requested changes
The new redirects/injects should have improved method names, otherwise, good stuff!

2020-02-07 04:29 UTC, gabizou commented on src/main/java/org/spongepowered/common/mixin/tracker/item/BoneMealItemMixin_Tracker.java
>          // Even though we're in a group, expecting this to succeed in forge environments will not work since there is a different mixin
Update the redirect method name to like `tracker$wrapGrowWithPhaseEntry`

2020-02-07 04:29 UTC, gabizou commented on src/main/java/org/spongepowered/common/mixin/tracker/world/end/DragonFightManagerMixin_Tracker.java
> +    private void trackDragonRespawn(DragonSpawnState dragonSpawnState, ServerWorld worldIn, DragonFightManager manager, List<EnderCrystalEntity> crystals, int respawnStateTicks, BlockPos exitPortalLo
The method name should follow the wiki conventions still: `tracker$wrapSpawnStateWithPhaseEntry` or think of a better name 😆

2020-02-07 12:59 UTC, ImMorpheus requested changes

2020-02-07 12:59 UTC, ImMorpheus commented on src/main/java/org/spongepowered/common/mixin/tracker/world/end/DragonFightManagerMixin_Tracker.java
> +package org.spongepowered.common.mixin.tracker.world.end;
Missing license

2020-02-09 17:57 UTC, gabizou approved these changes
I'll get to merge this in tonight.

2020-02-10 20:30 UTC, ImMorpheus approved these changes

2020-02-11 04:01 UTC, merged