Implement SaveChunkEvent.
SpongePowered/Sponge pull request #2551
Opened 2020-04-04 16:05 UTC by Zidane

For discussion, @dualspiral 

Also note I fixed the fact that we were calling LoadChunk on the client thread (or attempting to) as well as we were not respecting ShouldFire for unload.

Signed-off-by: Chris Sanders <zidane@spongepowered.org>

2020-04-04 16:26 UTC, dualspiral commented
I mean, it's bog standard throwing events and fixing bugs! I see nothing contentious here. If someone does, I'd be mightly surprised. When the API is good to go, this will be good to go.

2020-06-06 11:46 UTC, ImMorpheus requested changes
Checking the flag for the generic type will also make the event fire when there are listeners for other sub events but not the event itself.

2020-06-06 11:46 UTC, ImMorpheus commented on src/main/java/org/spongepowered/common/mixin/core/world/chunk/storage/AnvilChunkLoaderMixin.java
> +        if (ShouldFire.SAVE_CHUNK_EVENT || ShouldFire.SAVE_CHUNK_EVENT_POST) {
```suggestion
        if (ShouldFire.SAVE_CHUNK_EVENT_POST) {
```

2020-06-06 11:46 UTC, ImMorpheus commented on src/main/java/org/spongepowered/common/mixin/core/world/gen/ChunkProviderServerMixin.java
> +        if (ShouldFire.SAVE_CHUNK_EVENT || ShouldFire.SAVE_CHUNK_EVENT_PRE) {
```suggestion
        if (ShouldFire.SAVE_CHUNK_EVENT_PRE) {
```

2020-06-09 18:27 UTC, ImMorpheus approved these changes

2020-06-10 04:06 UTC, gabizou approved these changes
LGTM. Some reservations about changing `world.isRemote` to a `((WorldBridge) world).bridge$isFake()` but that isn't likely going to be an issue.

2020-06-10 17:48 UTC, merged