Implement LaunchProjectileEvent, Take 2
SpongePowered/Sponge pull request #2598
Opened 2020-05-06 08:14 UTC by RedNesto

This is an adapted version of #1769 for API 7

One big issue with the current event is that it is limited to one projectile, where mods (and crossbows in newer versions of the game) can shoot multiple at once. I'd like to fix that later for API 8 in another PR.

**What works**

- [x] A non-player entity shoots a projectile (skeletons shooting arrows, llamas spitting, ghasts shooting fireballs, snowmans shooting snowballs, blaze shooting small fireballs, withers, ender dragon)
  - [x] Cancelling, at least for vanilla entities, that shoot one projectile and not do not consume stacks from an inventory
- [x] A player shoots arrows
  - [x] Cancelling, if only one projectile is launched
  - [ ] Cancelling when several projectiles are shot (possible with mods) and only one is cancelled: this may restore all consumed stacks
- [x] A player throws projectiles (snowballs, eggs, potions - splash and lingering -, enderpearls, eyes of ender, using fishing rod, experience bottle)
  - [x] Cancelling (assuming it only launches one at a time)
- [x] A dispenser launches a projectile (arrows, snowballs, eggs, potions - splash and lingering -, experience bottle)
  - [x] Cancelling (assuming it only launches one at a time)
- [ ] A plugin shoots a projectile
- [ ] A player uses a firework - I had to add a condition operand, otherwise fireworks are always restored to the player's inventory. I need help on this one
  - [ ] Cancelling
- [x] A dispenser dispenses a firework
  - [x] Cancelling

There can be issues in cases where multiple projectiles are launched at the same time (but in vanilla it shouldn't be an issue). I think the best way to handle it is to cancel all events if one is cancelled.

2020-05-28 05:51 UTC, gabizou requested changes
Context leakage that should not exist outside a Stackframe, other comments are more clarification needed or some explanation fo what's going on (can even be some comments in code so people looking back at this will understand in the future ;) )

2020-05-28 05:51 UTC, gabizou commented on src/main/java/org/spongepowered/common/event/SpongeCommonEventFactory.java
> +    public static void callProjectileLaunchEvent(CauseStackManager.StackFrame frame, EntityPlayerMP player, List<Projectile> projectiles,
```suggestion
    public static void callProjectileLaunchEvent(final CauseStackManager.StackFrame frame, final EntityPlayerMP player, final List<Projectile> projectiles,
```

2020-05-28 05:51 UTC, gabizou commented on src/main/java/org/spongepowered/common/event/SpongeCommonEventFactory.java
> +            PhaseContext<?> context) {
```suggestion
            final PhaseContext<?> context) {
```

2020-05-28 05:51 UTC, gabizou commented on src/main/java/org/spongepowered/common/event/SpongeCommonEventFactory.java
> +            LaunchProjectileEvent event = SpongeEventFactory.createLaunchProjectileEvent(frame.getCurrentCause(), projectile);
```suggestion
            final LaunchProjectileEvent event = SpongeEventFactory.createLaunchProjectileEvent(frame.getCurrentCause(), projectile);
```

2020-05-28 05:51 UTC, gabizou commented on src/main/java/org/spongepowered/common/event/SpongeCommonEventFactory.java
> +     */
Gonna need a `@SuppressWarnings({"rawTypes", "uncheckedCast"})` or something for the raw `List` casting going on.

2020-05-28 05:51 UTC, gabizou commented on src/main/java/org/spongepowered/common/event/SpongeCommonEventFactory.java
> +            Optional<User> creator = Optional.of((User) player);
```suggestion
            final Optional<User> creator = Optional.of((User) player);
```

2020-05-28 05:51 UTC, gabizou commented on src/main/java/org/spongepowered/common/event/SpongeCommonEventFactory.java
> +                EntityUtil.processEntitySpawn(projectile, () -> creator);
Was almost sure there was a list based one that would work?

2020-05-28 05:51 UTC, gabizou commented on src/main/java/org/spongepowered/common/event/tracking/phase/block/DispensePhaseState.java
> +                List<Entity> rest = new ArrayList<>();
```suggestion
                final List<Entity> projectiles = new ArrayList<>();
                final List<Entity> rest = new ArrayList<>();
```

2020-05-28 05:51 UTC, gabizou commented on src/main/java/org/spongepowered/common/event/tracking/phase/block/DispensePhaseState.java
> +                    Sponge.getCauseStackManager().addContext(EventContextKeys.SPAWN_TYPE, SpawnTypes.DISPENSE);
Should not be adding to the context outside a frame, or without popping the context afterwards.

2020-05-28 05:51 UTC, gabizou commented on src/main/java/org/spongepowered/common/event/tracking/phase/block/DispensePhaseState.java
> +                        TileEntity tileEntity = phaseContext.getSource(BlockSnapshot.class)
Dispensing uses a `BlockSnapshot`? If you want to retain a reference to the original `TileEntity` and making this performant (we always do), make a specialized `PhaseContext` for `DispensePhaseState` that will take a `launcher(TileEntity)` and provide the nullable `TileEntity` that might be launching the projectile.

2020-05-28 05:51 UTC, gabizou commented on src/main/java/org/spongepowered/common/event/tracking/phase/block/DispensePhaseState.java
> +                        int projectilesCount = projectiles.size();
```suggestion
                        final int projectilesCount = projectiles.size();
```

2020-05-28 05:51 UTC, gabizou commented on src/main/java/org/spongepowered/common/event/tracking/phase/packet/player/InteractionPacketState.java
> +        ((TrackedInventoryBridge) playerMP.openContainer).bridge$setCaptureInventory(true);
I don't feel comfortable setting the inventory to capture blindly like this, are we for certain that this doesn't negatively interact with other inventory related captures that might take place when interacting with other bits (like right clicking a water bucket to a cauldron)

2020-05-28 05:51 UTC, gabizou commented on src/main/java/org/spongepowered/common/event/tracking/phase/packet/player/PlaceBlockPacketState.java
> +        boolean entityCaptured = !context.getCapturedEntities().isEmpty();
```suggestion
        final boolean entityCaptured = !context.getCapturedEntities().isEmpty();
```

2020-05-28 05:51 UTC, gabizou commented on src/main/java/org/spongepowered/common/event/tracking/phase/packet/player/PlaceBlockPacketState.java
> +                    List<Entity> rest = new ArrayList<>();
```suggestion
                    final List<Projectile> projectiles = new ArrayList<>();
                    final List<Entity> rest = new ArrayList<>();
```

2020-05-28 05:51 UTC, gabizou commented on src/main/java/org/spongepowered/common/event/tracking/phase/tick/EntityTickPhaseState.java
> +                                launchEventCancelled = true;
So if any of the launch events are cancelled, then how would you tell plugins that the events prior were cancelled?

2020-05-28 05:51 UTC, gabizou commented on src/main/java/org/spongepowered/common/mixin/core/block/BlockDispenserMixin.java
> +        ((DispenserBridge) dispenser).bridge$setDispensedItem(dispensedItem);
reset anywhere?

2020-05-28 05:51 UTC, gabizou commented on src/main/java/org/spongepowered/common/mixin/core/tileentity/TileEntityDispenserMixin.java
> +    private int originalStackSize;
```suggestion
    private @Nullable ItemStack impl$originalStack;
    private int impl$originalStackSize;
```

2020-05-28 05:51 UTC, gabizou commented on src/main/java/org/spongepowered/common/mixin/core/tileentity/TileEntityDispenserMixin.java
> +    private int originalStackSize;
You might as well make a snapshot instead.

2020-05-28 05:51 UTC, gabizou commented on src/main/java/org/spongepowered/common/mixin/core/tileentity/TileEntityDispenserMixin.java
> +        this.originalStack = dispensed;
You do know this is 100% mutable, or are you intending on copying it outside of this?

2020-05-28 05:51 UTC, gabizou commented on src/main/java/org/spongepowered/common/mixin/core/tileentity/TileEntityDispenserMixin.java
> +            this.originalStack.setCount(this.originalStackSize + count);
What is this restoring exactly? The field seems to exist solely to be stored and updated, but not actually read anywhere that I can see.

2020-05-28 13:55 UTC, dualspiral commented
It's also worth nothing [LaunchProjectileEvent has actually been deprecated](https://github.com/SpongePowered/SpongeAPI/commit/79fb019bd6245e8415016dcfc71a75242f298f55) and a [barebones firing of the event after spawning in the entity](https://github.com/SpongePowered/SpongeCommon/commit/8e4ee8e93e2acfc4f6b8c2349a0242950b8cd4df) was added for projectiles - the rationale being that when launching a projectile you're spawning an entity in anyway and the `Cause` should tell you why.

2020-05-28 14:08 UTC, RedNesto commented
Yeah I noticed it. I'm not sure if this PR is worth it, what is essentially adds is cancellation handling and context now.

2020-06-28 10:51 UTC, dualspiral commented
I think we'll leave it as is as we have a barebones event in 7 and it's completely gone in 8. Regardless, thanks for looking into this.

2020-06-28 10:51 UTC, closed without merging

2020-06-28 11:00 UTC, RedNesto commented
Agree, we'll need to make sure the context is correctly set for projectiles though (I'm not sure if it is properly filled right now).

2020-06-28 11:01 UTC, dualspiral commented
I'd be happy for a PR if that's the case!