Update ChatUtil from core:invalid #2987
SpongePowered/Sponge pull request #3099
Opened 2020-07-30 04:02 UTC by mailboxkiller

2020-07-30 04:05 UTC, mailboxkiller commented
fixes #2987

2020-08-06 22:12 UTC, JBYoshi requested changes

2020-08-06 22:12 UTC, JBYoshi commented on src/main/java/org/spongepowered/common/text/chat/ChatUtil.java
> +        final Component raw = TextComponent.builder(component.content()).build();
The `component` parameter should still be a Minecraft `ITextComponent`. You can convert it using the `SpongeAdventure` class.

2021-01-03 15:40 UTC, ImMorpheus commented
Fixed by https://github.com/SpongePowered/Sponge/commit/ae3b757134cadfe8ac0802bff194ff527ea2e77d

2021-01-03 15:40 UTC, closed without merging