[RFC] Introduce services for observability
SpongePowered/Sponge pull request #3296
Opened 2021-02-14 03:16 UTC by pschichtel

API PR: SpongePowered/SpongeApi#2298

So far this is only a few random metrics thrown in here to show how the prometheus metrics could be used here. I'm currently only using the global default registry (`CollectorRegistry.defaultRegistry()`, implicity used by the `.register()` calls.

I would expect a sane service implementation to scrape the default registry, so this should just work. Alternatively you could setup a new registry and add it to the `MetricsService` once it becomes available.

2021-02-14 17:51 UTC, kashike requested changes

2021-02-14 17:51 UTC, kashike commented on src/main/java/org/spongepowered/common/event/tracking/TrackingUtil.java
> +            .name("sponge_tracking_tileentity_tick_seconds")
```suggestion
            .name("sponge_tracking_blockentity_tick_seconds")
```

2021-02-14 17:51 UTC, kashike commented on src/main/java/org/spongepowered/common/event/tracking/TrackingUtil.java
> +            .name("sponge_tracking_tileentity_count")
```suggestion
            .name("sponge_tracking_blockentity_count")
```

2021-02-14 17:51 UTC, kashike commented on src/main/java/org/spongepowered/common/event/tracking/TrackingUtil.java
> +    private static final Histogram TILEENTITY_TICK_TIMER = Histogram.build()
```suggestion
    private static final Histogram BLOCKENTITY_TICK_TIMER = Histogram.build()
```

2021-02-14 17:51 UTC, kashike commented on src/main/java/org/spongepowered/common/event/tracking/TrackingUtil.java
> +    private static final Counter TRACKING_COUNTER = Counter.build()
Should mention "blockentity" in the field name to match the counter name.

2021-07-03 03:45 UTC, Zidane commented
@pschichtel Could you update this PR?

2021-07-03 08:57 UTC, pschichtel commented
> @pschichtel Could you update this PR?

done. Not sure on where the dependency needs to go, I simply placed it where timings already was.

Besides the dependency, this PR was mostly intended to give an example of how to use this stuff. I have no clue if these metrics are actually useful or what else could be useful. My intention was to leave that up to you. I don't have the time to dig into this.

2021-07-06 09:07 UTC, gabizou commented
I can take over the remaining bits of this PR to add a few various histograms and such. I've a fair idea on how to add more pieces of information that may help with observability.

2021-07-06 14:33 UTC, pschichtel commented
that would be awesome. I thought about extracting the observer plugin out of the CubeEngine project to act as a reference implementation for plugin devs, maybe that could even be moved to the existing observer repo we have here?

2021-07-07 00:52 UTC, gabizou commented
> that would be awesome. I thought about extracting the observer plugin out of the CubeEngine project to act as a reference implementation for plugin devs, maybe that could even be moved to the existing observer repo we have here?

Do you have a link to said project? I'm curious what metrics you've found would be beneficial

2021-07-07 00:57 UTC, pschichtel commented
https://github.com/CubeEngine/modules-extra/blob/master/observe/src/main/java/org/cubeengine/module/observe/metrics/impl/SpongeCollector.java

It's still using the old interfaces and not the observer library, but since you asked about the metrics.

2022-05-29 01:22 UTC, closed without merging