Add editor config and sort imports
SpongePowered/Sponge pull request #3395
Opened 2021-05-02 06:19 UTC by gabizou

2021-05-02 07:13 UTC, kashike requested changes

2021-05-02 07:13 UTC, kashike commented on .editorconfig
> +ij_java_imports_layout = $*,|,*,|,org.spongepowered.**,|,com.mojang.**,net.minecraft.**,|,javax.**,java.**
I'm not a fan of these separate import groups, can we just have imports normally please?

2021-05-08 15:58 UTC, ImMorpheus requested changes
This is not consistent with what we are doing in the API/checkstyle and what's written in the docs.

https://docs.spongepowered.org/stable/en/contributing/implementation/codestyle.html

I think we should PR this to the API to discover any issue with the current checkstyle config before tackling the implementation.
If needed, the docs should be updated to reflect the new guidelines.

2021-05-08 15:58 UTC, ImMorpheus commented on .editorconfig
> +max_line_length = 120
This should be 150.

2021-05-08 15:58 UTC, ImMorpheus commented on .editorconfig
> +ij_java_imports_layout = $*,|,*,|,org.spongepowered.**,|,com.mojang.**,net.minecraft.**,|,javax.**,java.**
> Imports must be grouped in the following order, where each group is separated by an empty line
> 
>     Static imports
> 
>     All other imports
> 
>     java imports
> 
>     javax imports

2021-07-03 03:43 UTC, Zidane commented
Closing this as we need to have a much more inclusive discussion as a dev team on editor formatting changes.

2021-07-03 03:43 UTC, closed without merging