Add world save mode for ServerWorld#save() to support flush
SpongePowered/Sponge pull request #3688
Opened 2022-05-17 14:58 UTC by Lignium

SpongeAPI | **Sponge**

2023-01-20 19:25 UTC, ImMorpheus requested changes
There are some changes in behaviour with serialization behaviour and events that seem unrelated to this PR.

2023-01-20 19:25 UTC, ImMorpheus commented on src/mixins/java/org/spongepowered/common/mixin/api/minecraft/server/level/ServerLevelMixin_API.java
> +        if (!serializationBehavior.equals(SerializationBehavior.MANUAL) &&
Why ? This is changing behaviour and it decreasing coverage in the Overwrite below since the serialization behaviour will never be `AUTOMATIC` after this if.

2023-01-20 19:25 UTC, ImMorpheus commented on src/mixins/java/org/spongepowered/common/mixin/core/server/level/ServerLevelMixin.java
> -        if (Sponge.eventManager().post(SpongeEventFactory.createSaveWorldEventPre(currentCause, ((ServerWorld) this)))) {
This is changing behaviour, why is the event not fired ? 

Note: it might make sense to not fire the event when serialization behaviour is `NONE` but it needs documentation and it does not seem to be what is happening here.

2023-01-20 19:41 UTC, Lignium commented on src/mixins/java/org/spongepowered/common/mixin/core/server/level/ServerLevelMixin.java
> -        if (Sponge.eventManager().post(SpongeEventFactory.createSaveWorldEventPre(currentCause, ((ServerWorld) this)))) {
It turns out that this event is always fired, even if the save operation will not performed, and Post is not fired.

2023-01-20 19:54 UTC, ImMorpheus commented on src/mixins/java/org/spongepowered/common/mixin/core/server/level/ServerLevelMixin.java
> -        if (Sponge.eventManager().post(SpongeEventFactory.createSaveWorldEventPre(currentCause, ((ServerWorld) this)))) {
> Note: it might make sense to not fire the event when serialization behaviour is NONE but it needs documentation and it does not seem to be what is happening here.

On second thought, this is probably a breaking change so it needs to be fired regardless. We can change it in api-10 but if this targets api-8 the event needs to fire.

2023-01-21 12:43 UTC, aromaa requested changes
I have made the fixes to the SerializationBehavior logic in 3a371bb06138134242ec0d706bccd8b7f909ba8a that were discussed on Discord.

We can take a look at how the events should be fired on api-10 but for api-8 it would be a breaking change.

2024-06-28 20:30 UTC, closed without merging