Add missing data conversion for BlockStateKeys
SpongePowered/Sponge pull request #3864
Opened 2023-06-11 20:14 UTC by Lignium

Primitive types and mixins can cast freely, but types like `Direction` and `Axis` are not mixins and cannot cast on their own.

2023-06-11 21:58 UTC, aromaa requested changes
We already seem to have similar logic in `StateHolderMixin_API`. This should be easier to do by casting to our `BlockState` to achieve the same?

2023-06-11 22:37 UTC, Lignium commented
> We already seem to have similar logic in `StateHolderMixin_API`. This should be easier to do by casting to our `BlockState` to achieve the same?

Yes, this also works, moreover, I did not take into account all the data initially.

2023-06-12 17:21 UTC, aromaa commented on src/main/java/org/spongepowered/common/data/provider/block/state/BlockStateDataProvider.java
> +                    });
```suggestion
                .get(bs -> ((org.spongepowered.api.block.BlockState) bs).stateProperty((StateProperty<T>) property).orElse(null))
                .set((bs, v) -> (BlockState) ((org.spongepowered.api.block.BlockState) bs).withStateProperty((StateProperty<T>) property, v).orElse((org.spongepowered.api.block.BlockState) bs));
```
We generally return the last `BlockState` if the offered value is invalid. The contract says that we return empty optional if the key is not supported.

2023-06-12 17:24 UTC, Lignium commented on src/main/java/org/spongepowered/common/data/provider/block/state/BlockStateDataProvider.java
> +                    });
> We generally return the last `BlockState` if the offered value is invalid. The contract says that we return empty optional if the key is not supported.

Exactly, I missed that

2023-06-12 17:40 UTC, aromaa approved these changes
Thank you!!

2023-06-12 17:40 UTC, merged