Enchantement ids were not retrieved correctly during deserialization
SpongePowered/Sponge pull request #3906
Opened 2023-10-18 17:31 UTC by AlexandreArcil

### Version
Minecraft: 1.19.4
SpongeAPI: 10.1.0-SNAPSHOT
Sponge: 1.19.4-10.1.0-SNAPSHOT
SpongeVanilla: 1.19.4-10.0.0-RC0

### The bug
The deserialization of an enchanted item in a config file produces an item without its enchantments.  
Reported by #3904.

### Description
During the deserilization of an enchanted item, it will first create a `CompoundTag` from `UnsafeData` and then fix the enchantment data. The problem is that the enchantment ids in the `CompoundTag` are String which represent the resource location of an enchantment but they were retrieved as short. As a result, the modified `CompoundTag` contained enchantment ids with "0s" as value.
After that, if the enchantments were retrieved from the itemstack, the Optional was empty because it couldn't retrieved the enchantment type from the incorrect value "0s".

### The fix
The fix is to retrieve and set as a string the enchantment id in the nbt and not as a short.

2023-10-22 18:33 UTC, SawFowl commented
#3904

2023-11-02 23:22 UTC, aromaa requested changes
Should be fine by just removing the enchantment id altogether as its a string and does not need fixup for its type.
```java
final CompoundTag nbttagcompound = nbttaglist.getCompound(i);
final short lvl = nbttagcompound.getShort(Constants.Item.ITEM_ENCHANTMENT_LEVEL);

nbttagcompound.putShort(Constants.Item.ITEM_ENCHANTMENT_LEVEL, lvl);
```

2023-11-05 13:36 UTC, AlexandreArcil commented
Done !

2023-11-05 16:19 UTC, aromaa approved these changes
LGTM. Thank you!

2023-11-05 16:20 UTC, merged