Auth event called twice
SpongePowered/Sponge pull request #3911
Opened 2023-10-29 10:48 UTC by AlexandreArcil

## Version
Minecraft: 1.20.2
SpongeAPI: 11.0.0-SNAPSHOT
Sponge: 1.20.2-11.0.0-SNAPSHOT
SpongeVanilla: 1.20.2-11.0.0-RC0

## The bug
During the login of a player, the event `ServerSideConnectionEvent.Auth` was called twice.

## Description
When a player logs in, the event `ServerSideConnectionEvent.Auth` is called for the first time by `ServerLoginPacketListenerImplMixin` and then by `ServerLoginPacketListenerImpl_1Mixin` if the server is on online mode, but and not called if it is on offline mode.
The reason for this is due to how the mixin `ServerLoginPacketListenerImpl#impl$fireAuthEventOffline` was injected: at the assignment of the field _state_ with the value KEY. In API-10 (1.19.4), this was done in singleplayer or if the server is in offline mode, but on API-11 (1.20.2), this is done if the server is on online mode. Later in the login process, the mixin `ServerLoginPacketListenerImpl_1Mixin` will trigger the event if the player was authenticated on an online server.

## The fix
As the name suggests, `fireAuthEventOffline` should only call the event when the server is in offline mode.
The fix changes the injection point to the method `startClientVerification` because it's called when the server is in offline mode. It then checks whether if the game profile given as argument is an "offline profile". This is done by comparing it with the result of a call to the method `createOfflineProfile` because the profile argument comes from that method (ie: `this.startClientVerification(createOfflineProfile(this.requestedUsername))`).

`startClientVerification` is also called in other cases: when it is on a singleplayer, but we were in the context of a server, and when the player is authenticated to the server, but the check skips the event trigger.

2023-11-11 20:38 UTC, ImMorpheus requested changes

2023-11-11 20:38 UTC, ImMorpheus commented on src/mixins/java/org/spongepowered/common/mixin/core/server/network/ServerLoginPacketListenerImplMixin.java
> +    @Shadow protected static GameProfile createOfflineProfile(String $$0) {
Can you group this with the other shadow methods at the top of the class ?

2023-11-11 20:38 UTC, ImMorpheus commented on src/mixins/java/org/spongepowered/common/mixin/core/server/network/ServerLoginPacketListenerImplMixin.java
> +    @Inject(method = "startClientVerification(Lcom/mojang/authlib/GameProfile;)V", at = @At("HEAD"), cancellable = true)
I don't think we need to change the injection point.

In 1.19 this was injecting to right before retrieving the static field `ServerLoginPacketListenerImpl.State.READY_TO_ACCEPT` which was removed in 1.20 and replaced with the call to `startClientVerification`.

When updating to 1.20 the injection target was changed to `ServerLoginPacketListenerImpl.State.KEY` which is accessed when the server is online.

I think we should still inject in `handleHello` but update the `at` target to call before `startClientVerification`

2023-11-11 20:38 UTC, ImMorpheus commented on src/mixins/java/org/spongepowered/common/mixin/core/server/network/ServerLoginPacketListenerImplMixin.java
> +        if(gameProfile.equals(createOfflineProfile(gameProfile.getName()))) {
See above, we should remove this condition and update the injection point to the correct method

2023-11-12 19:01 UTC, AlexandreArcil commented
Ok I changed the injection point to what you wanted !

2023-11-12 19:31 UTC, ImMorpheus commented
Thanks! Can you rebase on api-11 ?

2023-11-13 18:16 UTC, AlexandreArcil commented
Done!

2023-11-13 18:57 UTC, ImMorpheus commented
I don't think that's it, the PR has ~30 commits.

Please see https://docs.spongepowered.org/stable/en/contributing/howtogit.html

2023-11-14 18:19 UTC, AlexandreArcil commented
Ok I did some force push and now everything is correct, no ?

2023-11-14 21:12 UTC, merged

2023-11-14 21:13 UTC, ImMorpheus commented
Yep, thank you!