Zero and negative one item stack quantities
SpongePowered/Sponge pull request #996
Opened 2016-10-23 19:41 UTC by Desetude

[API](https://github.com/SpongePowered/SpongeAPI/pull/1397), Common

As discussed at https://github.com/SpongePowered/SpongeAPI/issues/1392, a -1 quantity would be useful for ignoring stack size differences with `Inventory#query(ItemStack)` and as discussed at https://github.com/SpongePowered/SpongeCommon/issues/150, a 0 quantity would be useful for menus.

In my implementation I have added `Inventory#unsafeQuantity(int)` which allows -1, 0 and any positive quantity.

2016-10-23 19:43 UTC, kashike requested changes

2016-10-23 19:43 UTC, kashike commented on src/main/java/org/spongepowered/common/item/inventory/SpongeItemStackBuilder.java
> +    @Override public ItemStack.Builder unsafeQuantity(int quantity) {
Wrong formatting.
```java
    @Override
    public ItemStack.Builder unsafeQuantity(int quantity) {
```

2016-10-23 21:07 UTC, ryantheleach commented
Why are you limiting this to -1 and 0 only?

2016-10-23 21:36 UTC, Desetude commented
> Why are you limiting this to -1 and 0 only?

As they're the only quantities I have seen uses for, but after the conversation at https://github.com/SpongePowered/SpongeAPI/pull/1397 I have decided I'm only going to allow 0.

2016-12-17 11:26 UTC, Faithcaio commented
Negative or zero ItemStack quantities ALWAYS result in an "empty" Air Itemstack in 1.11:
We were able to bypass this in our mixins but this is now fixed with https://github.com/SpongePowered/SpongeCommon/commit/c2965edba2f12f63ecddac812223222541b76709.

Currently the API javadocs for Inventory#query(itemstack) are wrong: All ItemStack quantities are ignored: see matching logic in `ItemStackStrategy`

2016-12-17 11:26 UTC, closed without merging